"""Service classes generated from the Forward API description.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from forward_sdk._async.services._generated.aliases import AsyncAliasesService
from forward_sdk._async.services._generated.bgp_advertisements import AsyncBGPAdvertisementsService
from forward_sdk._async.services._generated.change_set_directories import (
    AsyncChangeSetDirectoriesService,
)
from forward_sdk._async.services._generated.checks import AsyncChecksService
from forward_sdk._async.services._generated.classic_devices import AsyncClassicDevicesService
from forward_sdk._async.services._generated.collection_schedules import (
    AsyncCollectionSchedulesService,
)
from forward_sdk._async.services._generated.collector_tasks import AsyncCollectorTasksService
from forward_sdk._async.services._generated.configuration import AsyncConfigurationService
from forward_sdk._async.services._generated.credentials import AsyncCredentialsService
from forward_sdk._async.services._generated.data_connectors import AsyncDataConnectorsService
from forward_sdk._async.services._generated.data_files import AsyncDataFilesService
from forward_sdk._async.services._generated.encryptors import AsyncEncryptorsService
from forward_sdk._async.services._generated.endpoint_profiles import AsyncEndpointProfilesService
from forward_sdk._async.services._generated.firewall_predict import AsyncFirewallPredictService
from forward_sdk._async.services._generated.internet_node import AsyncInternetNodeService
from forward_sdk._async.services._generated.intranet_nodes import AsyncIntranetNodesService
from forward_sdk._async.services._generated.jump_servers import AsyncJumpServersService
from forward_sdk._async.services._generated.l2vpns import AsyncL2vpnsService
from forward_sdk._async.services._generated.l3vpns import AsyncL3vpnsService
from forward_sdk._async.services._generated.legacy_collection import AsyncLegacyCollectionService
from forward_sdk._async.services._generated.network_endpoints import AsyncNetworkEndpointsService
from forward_sdk._async.services._generated.network_locations import AsyncNetworkLocationsService
from forward_sdk._async.services._generated.network_topology import AsyncNetworkTopologyService
from forward_sdk._async.services._generated.path_search import AsyncPathSearchService
from forward_sdk._async.services._generated.predict_assist import AsyncPredictAssistService
from forward_sdk._async.services._generated.snapshot_diff_details import (
    AsyncSnapshotDiffDetailsService,
)
from forward_sdk._async.services._generated.system_administration import (
    AsyncSystemAdministrationService,
)
from forward_sdk._async.services._generated.user_accounts import AsyncUserAccountsService
from forward_sdk._async.services._generated.vulnerability_analysis import (
    AsyncVulnerabilityAnalysisService,
)
from forward_sdk._async.services._generated.wan_circuits import AsyncWANCircuitsService
from forward_sdk._async.services._generated.webhooks import AsyncWebhooksService

if TYPE_CHECKING:  # pragma: no cover
    from forward_sdk._async.transport import AsyncTransport

__all__ = [
    "AsyncAliasesService",
    "AsyncBGPAdvertisementsService",
    "AsyncChangeSetDirectoriesService",
    "AsyncChecksService",
    "AsyncClassicDevicesService",
    "AsyncCollectionSchedulesService",
    "AsyncCollectorTasksService",
    "AsyncConfigurationService",
    "AsyncCredentialsService",
    "AsyncDataConnectorsService",
    "AsyncDataFilesService",
    "AsyncEncryptorsService",
    "AsyncEndpointProfilesService",
    "AsyncFirewallPredictService",
    "AsyncGeneratedServices",
    "AsyncInternetNodeService",
    "AsyncIntranetNodesService",
    "AsyncJumpServersService",
    "AsyncL2vpnsService",
    "AsyncL3vpnsService",
    "AsyncLegacyCollectionService",
    "AsyncNetworkEndpointsService",
    "AsyncNetworkLocationsService",
    "AsyncNetworkTopologyService",
    "AsyncPathSearchService",
    "AsyncPredictAssistService",
    "AsyncSnapshotDiffDetailsService",
    "AsyncSystemAdministrationService",
    "AsyncUserAccountsService",
    "AsyncVulnerabilityAnalysisService",
    "AsyncWANCircuitsService",
    "AsyncWebhooksService",
]


class AsyncGeneratedServices:
    """The API groups whose services are generated.

    Declared as attributes rather than attached dynamically so that type
    checkers and editors can see them.
    """

    aliases: AsyncAliasesService
    bgp_advertisements: AsyncBGPAdvertisementsService
    change_set_directories: AsyncChangeSetDirectoriesService
    checks: AsyncChecksService
    classic_devices: AsyncClassicDevicesService
    collection_schedules: AsyncCollectionSchedulesService
    collector_tasks: AsyncCollectorTasksService
    configuration: AsyncConfigurationService
    credentials: AsyncCredentialsService
    data_connectors: AsyncDataConnectorsService
    data_files: AsyncDataFilesService
    encryptors: AsyncEncryptorsService
    endpoint_profiles: AsyncEndpointProfilesService
    firewall_predict: AsyncFirewallPredictService
    internet_node: AsyncInternetNodeService
    intranet_nodes: AsyncIntranetNodesService
    jump_servers: AsyncJumpServersService
    l2vpns: AsyncL2vpnsService
    l3vpns: AsyncL3vpnsService
    legacy_collection: AsyncLegacyCollectionService
    network_endpoints: AsyncNetworkEndpointsService
    network_locations: AsyncNetworkLocationsService
    network_topology: AsyncNetworkTopologyService
    path_search: AsyncPathSearchService
    predict_assist: AsyncPredictAssistService
    snapshot_diff_details: AsyncSnapshotDiffDetailsService
    system_administration: AsyncSystemAdministrationService
    user_accounts: AsyncUserAccountsService
    vulnerability_analysis: AsyncVulnerabilityAnalysisService
    wan_circuits: AsyncWANCircuitsService
    webhooks: AsyncWebhooksService

    def _attach_generated_services(self, transport: AsyncTransport) -> None:
        self.aliases = AsyncAliasesService(transport)
        self.bgp_advertisements = AsyncBGPAdvertisementsService(transport)
        self.change_set_directories = AsyncChangeSetDirectoriesService(transport)
        self.checks = AsyncChecksService(transport)
        self.classic_devices = AsyncClassicDevicesService(transport)
        self.collection_schedules = AsyncCollectionSchedulesService(transport)
        self.collector_tasks = AsyncCollectorTasksService(transport)
        self.configuration = AsyncConfigurationService(transport)
        self.credentials = AsyncCredentialsService(transport)
        self.data_connectors = AsyncDataConnectorsService(transport)
        self.data_files = AsyncDataFilesService(transport)
        self.encryptors = AsyncEncryptorsService(transport)
        self.endpoint_profiles = AsyncEndpointProfilesService(transport)
        self.firewall_predict = AsyncFirewallPredictService(transport)
        self.internet_node = AsyncInternetNodeService(transport)
        self.intranet_nodes = AsyncIntranetNodesService(transport)
        self.jump_servers = AsyncJumpServersService(transport)
        self.l2vpns = AsyncL2vpnsService(transport)
        self.l3vpns = AsyncL3vpnsService(transport)
        self.legacy_collection = AsyncLegacyCollectionService(transport)
        self.network_endpoints = AsyncNetworkEndpointsService(transport)
        self.network_locations = AsyncNetworkLocationsService(transport)
        self.network_topology = AsyncNetworkTopologyService(transport)
        self.path_search = AsyncPathSearchService(transport)
        self.predict_assist = AsyncPredictAssistService(transport)
        self.snapshot_diff_details = AsyncSnapshotDiffDetailsService(transport)
        self.system_administration = AsyncSystemAdministrationService(transport)
        self.user_accounts = AsyncUserAccountsService(transport)
        self.vulnerability_analysis = AsyncVulnerabilityAnalysisService(transport)
        self.wan_circuits = AsyncWANCircuitsService(transport)
        self.webhooks = AsyncWebhooksService(transport)


#: API group name to the client attribute carrying its service.
SERVICE_TAGS: dict[str, str] = {
    "Aliases": "aliases",
    "BGP Advertisements": "bgp_advertisements",
    "Change Set Directories": "change_set_directories",
    "Checks": "checks",
    "Classic Devices": "classic_devices",
    "Collection Schedules": "collection_schedules",
    "Collector Tasks": "collector_tasks",
    "Configuration": "configuration",
    "Credentials": "credentials",
    "Data Connectors": "data_connectors",
    "Data Files": "data_files",
    "Encryptors": "encryptors",
    "Endpoint Profiles": "endpoint_profiles",
    "Firewall Predict": "firewall_predict",
    "Internet Node": "internet_node",
    "Intranet Nodes": "intranet_nodes",
    "Jump Servers": "jump_servers",
    "L2VPNs": "l2vpns",
    "L3VPNs": "l3vpns",
    "Legacy Collection": "legacy_collection",
    "Network Endpoints": "network_endpoints",
    "Network Locations": "network_locations",
    "Network Topology": "network_topology",
    "Path Search": "path_search",
    "Predict Assist": "predict_assist",
    "Snapshot Diff Details": "snapshot_diff_details",
    "System Administration": "system_administration",
    "User Accounts": "user_accounts",
    "Vulnerability Analysis": "vulnerability_analysis",
    "WAN Circuits": "wan_circuits",
    "Webhooks": "webhooks",
}
