"""Adjacent Networks.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncAdjacentNetworksService"]


class AsyncAdjacentNetworksService(AsyncService):
    """Adjacent Networks."""

    async def add_adjacent_network_connection(
        self,
        *,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add one connection to an adjacent network.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["addAdjacentNetworkConnection"](
                network_id=self._network(network_id), device_name=device_name, body=body
            )
        )
        return payload

    async def backdate_adjacent_networks(
        self,
        *,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> Any:
        """Apply recent adjacent network changes to an existing snapshot.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["backdateAdjacentNetworks"](
                network_id=self._network(network_id), snapshot_id=self._snapshot(snapshot_id)
            )
        )
        return payload

    async def compute_adjacent_network_connections(
        self,
        *,
        query_id: str,
        network_id: str | None = None,
    ) -> models.L3DynamicConnectionsComputeResult:
        """Preview the connections an NQE query would produce.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["computeAdjacentNetworkConnections"](
                network_id=self._network(network_id), query_id=query_id
            )
        )
        return models.L3DynamicConnectionsComputeResult.model_validate(payload or {})

    async def delete_adjacent_network(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete an adjacent network.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteAdjacentNetwork"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return payload

    async def delete_adjacent_network_connections(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Remove the connections matching every given filter.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteAdjacentNetworkConnections"](
                network_id=self._network(network_id),
                device_name=device_name,
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    async def get_adjacent_network(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> models.AdjacentNetwork:
        """One adjacent network.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getAdjacentNetwork"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return models.AdjacentNetwork.model_validate(payload or {})

    async def get_adjacent_network_connections(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """An adjacent network's connections, optionally filtered.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getAdjacentNetworkConnections"](
                network_id=self._network(network_id),
                device_name=device_name,
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    async def get_adjacent_networks(
        self,
        *,
        network_id: str | None = None,
    ) -> models.AdjacentNetworkList:
        """The network's adjacent networks.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getAdjacentNetworks"](network_id=self._network(network_id))
        )
        return models.AdjacentNetworkList.model_validate(payload or {})

    async def patch_adjacent_network(
        self,
        *,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.AdjacentNetwork:
        """Change an adjacent network.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchAdjacentNetwork"](
                network_id=self._network(network_id), device_name=device_name, body=body
            )
        )
        return models.AdjacentNetwork.model_validate(payload or {})

    async def put_adjacent_network(
        self,
        *,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Create or replace an adjacent network.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putAdjacentNetwork"](
                network_id=self._network(network_id), device_name=device_name, body=body
            )
        )
        return payload

    async def put_adjacent_networks(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace all of the network's adjacent networks.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putAdjacentNetworks"](network_id=self._network(network_id), body=body)
        )
        return payload
