"""Checks.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncChecksService"]


class AsyncChecksService(AsyncService):
    """Checks."""

    async def add_check(
        self,
        *,
        snapshot_id: str,
        body: Any,
        persistent: bool | None = None,
    ) -> models.NetworkCheckResult:
        """Add a check."""
        payload = await self._send_json(
            ops.BUILDERS["addCheck"](snapshot_id=snapshot_id, body=body, persistent=persistent)
        )
        return models.NetworkCheckResult.model_validate(payload or {})

    async def deactivate_check(
        self,
        *,
        snapshot_id: str,
        check_id: str,
    ) -> Any:
        """Deactivate a check."""
        payload = await self._send_json(
            ops.BUILDERS["deactivateCheck"](snapshot_id=snapshot_id, check_id=check_id)
        )
        return payload

    async def deactivate_checks(
        self,
        *,
        snapshot_id: str,
    ) -> Any:
        """Deactivate all checks."""
        payload = await self._send_json(ops.BUILDERS["deactivateChecks"](snapshot_id=snapshot_id))
        return payload

    async def get_available_predefined_checks(
        self,
    ) -> list[models.AvailablePredefinedCheck]:
        """Get available Predefined checks."""
        payload = await self._send_json(ops.BUILDERS["getAvailablePredefinedChecks"]())
        return [models.AvailablePredefinedCheck.model_validate(row) for row in payload or []]

    async def get_check(
        self,
        *,
        snapshot_id: str,
        check_id: str,
    ) -> models.NetworkCheckResultWithDiagnosis:
        """Get a check (with status)."""
        payload = await self._send_json(
            ops.BUILDERS["getCheck"](snapshot_id=snapshot_id, check_id=check_id)
        )
        return models.NetworkCheckResultWithDiagnosis.model_validate(payload or {})

    async def get_checks(
        self,
        *,
        snapshot_id: str,
        type: Sequence[str] | None = None,
        priority: Sequence[str] | None = None,
        status: Sequence[str] | None = None,
    ) -> list[models.NetworkCheckResult]:
        """Get checks (with status)."""
        payload = await self._send_json(
            ops.BUILDERS["getChecks"](
                snapshot_id=snapshot_id, type=type, priority=priority, status=status
            )
        )
        return [models.NetworkCheckResult.model_validate(row) for row in payload or []]
