"""Classic Devices.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncClassicDevicesService"]


class AsyncClassicDevicesService(AsyncService):
    """Classic Devices."""

    async def add_classic_device(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.ClassicDevice:
        """Add a new classic device.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["addClassicDevice"](network_id=self._network(network_id), body=body)
        )
        return models.ClassicDevice.model_validate(payload or {})

    async def add_classic_devices(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add new classic devices.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["addClassicDevices"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def delete_all_classic_devices(
        self,
        *,
        network_id: str | None = None,
    ) -> Any:
        """Delete all of a network's classic devices.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteAllClassicDevices"](network_id=self._network(network_id))
        )
        return payload

    async def delete_classic_device(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a classic device.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteClassicDevice"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return payload

    async def delete_classic_devices(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Delete specific classic devices.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteClassicDevices"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def get_classic_device(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
        with_: Sequence[str] | None = None,
    ) -> models.ClassicDevice:
        """Get a classic device.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getClassicDevice"](
                network_id=self._network(network_id), device_name=device_name, with_=with_
            )
        )
        return models.ClassicDevice.model_validate(payload or {})

    async def get_classic_devices(
        self,
        *,
        network_id: str | None = None,
        with_: Sequence[str] | None = None,
    ) -> models.ClassicDevices:
        """Get all classic devices.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getClassicDevices"](network_id=self._network(network_id), with_=with_)
        )
        return models.ClassicDevices.model_validate(payload or {})

    async def get_specific_classic_devices(
        self,
        *,
        body: Any,
        network_id: str | None = None,
        with_: Sequence[str] | None = None,
    ) -> models.ClassicDevices:
        """Get specific classic devices.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getSpecificClassicDevices"](
                network_id=self._network(network_id), body=body, with_=with_
            )
        )
        return models.ClassicDevices.model_validate(payload or {})

    async def patch_classic_device(
        self,
        *,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.ClassicDevice:
        """Update a classic device.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchClassicDevice"](
                network_id=self._network(network_id), device_name=device_name, body=body
            )
        )
        return models.ClassicDevice.model_validate(payload or {})

    async def patch_classic_devices(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Update specific classic devices.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchClassicDevices"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def put_classic_device(
        self,
        *,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.ClassicDevice:
        """Add or update a classic device.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putClassicDevice"](
                network_id=self._network(network_id), device_name=device_name, body=body
            )
        )
        return models.ClassicDevice.model_validate(payload or {})

    async def put_classic_devices(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add or update classic devices.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putClassicDevices"](network_id=self._network(network_id), body=body)
        )
        return payload
