"""Cloud Accounts.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncCloudAccountsService"]


class AsyncCloudAccountsService(AsyncService):
    """Cloud Accounts."""

    async def create_cloud_account(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.CloudAccount:
        """Add a cloud account.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["createCloudAccount"](network_id=self._network(network_id), body=body)
        )
        return models.CloudAccount.model_validate(payload or {})

    async def delete_cloud_account(
        self,
        *,
        account_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Remove a cloud account.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteCloudAccount"](
                network_id=self._network(network_id), account_name=account_name
            )
        )
        return payload

    async def discover_cloud_accounts(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.CloudAccountDiscoveryResult:
        """Discover accounts reachable with a credential, before creating one.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["discoverCloudAccounts"](network_id=self._network(network_id), body=body)
        )
        return models.CloudAccountDiscoveryResult.model_validate(payload or {})

    async def discover_cloud_sub_accounts(
        self,
        *,
        account_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.CloudAccountDiscoveryResult:
        """Discover the sub-accounts, projects or subscriptions reachable from an existing account.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["discoverCloudSubAccounts"](
                network_id=self._network(network_id), account_name=account_name, body=body
            )
        )
        return models.CloudAccountDiscoveryResult.model_validate(payload or {})

    async def get_aws_assume_role_external_id(
        self,
        *,
        network_id: str | None = None,
    ) -> models.AwsExternalId:
        """The external id to put in an AWS assume-role trust policy.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getAwsAssumeRoleExternalId"](network_id=self._network(network_id))
        )
        return models.AwsExternalId.model_validate(payload or {})

    async def get_cloud_account_credential(
        self,
        *,
        account_name: str,
        network_id: str | None = None,
    ) -> Any:
        """The non-secret part of an account's credential.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getCloudAccountCredential"](
                network_id=self._network(network_id), account_name=account_name
            )
        )
        return payload

    async def list_aws_regions(
        self,
    ) -> Any:
        """AWS region ids and display names.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["listAwsRegions"]())
        return payload

    async def list_azure_environments(
        self,
    ) -> Any:
        """Azure environment ids and display names.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["listAzureEnvironments"]())
        return payload

    async def list_cloud_accounts(
        self,
        *,
        network_id: str | None = None,
    ) -> list[models.CloudAccountWithMeta]:
        """A network's cloud accounts, with their test results.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["listCloudAccounts"](network_id=self._network(network_id))
        )
        return [models.CloudAccountWithMeta.model_validate(row) for row in payload or []]

    async def list_gcp_regions(
        self,
    ) -> Any:
        """GCP region ids and display names.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["listGcpRegions"]())
        return payload

    async def list_ibm_regions(
        self,
    ) -> Any:
        """IBM Cloud region ids and display names.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["listIbmRegions"]())
        return payload

    async def list_newly_discovered_cloud_accounts(
        self,
        *,
        network_id: str | None = None,
    ) -> models.DiscoveredAccountsByAccount:
        """Sub-accounts discovery found that are not yet configured, per account.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["listNewlyDiscoveredCloudAccounts"](network_id=self._network(network_id))
        )
        return models.DiscoveredAccountsByAccount.model_validate(payload or {})

    async def set_cloud_account_credential(
        self,
        *,
        account_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.CloudAccount:
        """Replace an account's credential.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["setCloudAccountCredential"](
                network_id=self._network(network_id), account_name=account_name, body=body
            )
        )
        return models.CloudAccount.model_validate(payload or {})

    async def test_cloud_account_connectivity(
        self,
        *,
        account_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Test an existing account's connectivity.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["testCloudAccountConnectivity"](
                network_id=self._network(network_id), account_name=account_name, body=body
            )
        )
        return payload

    async def test_cloud_connectivity(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Test connectivity with a credential, before creating an account.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["testCloudConnectivity"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def update_cloud_account(
        self,
        *,
        account_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.CloudAccount:
        """Change a cloud account's settings.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateCloudAccount"](
                network_id=self._network(network_id), account_name=account_name, body=body
            )
        )
        return models.CloudAccount.model_validate(payload or {})
