"""Configuration.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncConfigurationService"]


class AsyncConfigurationService(AsyncService):
    """Configuration."""

    async def clear_org_config_value(
        self,
        *,
        property: str,
    ) -> Any:
        """Remove the calling user's org override, reverting to the default.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["clearOrgConfigValue"](property=property))
        return payload

    async def clear_org_scoped_config_value(
        self,
        *,
        org_id: str,
        property: str,
    ) -> Any:
        """Remove a named org's override, reverting to the default.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["clearOrgScopedConfigValue"](org_id=org_id, property=property)
        )
        return payload

    async def get_global_config_value(
        self,
        *,
        property: str,
    ) -> models.ConfigValue:
        """An org property's global default.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["getGlobalConfigValue"](property=property))
        return models.ConfigValue.model_validate(payload or {})

    async def get_org_config_value(
        self,
        *,
        property: str,
    ) -> models.ConfigValue:
        """An org property's effective value for the calling user's org.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["getOrgConfigValue"](property=property))
        return models.ConfigValue.model_validate(payload or {})

    async def get_org_scoped_config_value(
        self,
        *,
        org_id: str,
        property: str,
    ) -> models.ConfigValue:
        """An org property's effective value for a named org.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["getOrgScopedConfigValue"](org_id=org_id, property=property)
        )
        return models.ConfigValue.model_validate(payload or {})

    async def set_global_config_value(
        self,
        *,
        property: str,
        value: str,
    ) -> models.ConfigValue:
        """Change an org property's global default.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["setGlobalConfigValue"](property=property, value=value)
        )
        return models.ConfigValue.model_validate(payload or {})

    async def set_org_config_value(
        self,
        *,
        property: str,
        value: str,
    ) -> models.ConfigValue:
        """Set an org property for the calling user's org.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["setOrgConfigValue"](property=property, value=value)
        )
        return models.ConfigValue.model_validate(payload or {})

    async def set_org_scoped_config_value(
        self,
        *,
        org_id: str,
        property: str,
        value: str,
    ) -> models.ConfigValue:
        """Set an org property for a named org.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["setOrgScopedConfigValue"](org_id=org_id, property=property, value=value)
        )
        return models.ConfigValue.model_validate(payload or {})
