"""Data Files.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._ops import rest as ops

__all__ = ["AsyncDataFilesService"]


class AsyncDataFilesService(AsyncService):
    """Data Files."""

    async def get_data_files(
        self,
        *,
        network_id: str | None = None,
        view: str | None = None,
        snapshot_id: str | None = None,
    ) -> Any:
        """List the data files collected for a network.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getDataFiles"](
                network_id=self._network(network_id),
                view=view,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return payload
