"""Endpoint Profiles.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncEndpointProfilesService"]


class AsyncEndpointProfilesService(AsyncService):
    """Endpoint Profiles.

    May be unavailable on your instance (admin); see docs/gating.md.
    """

    async def create_cli_endpoint_profile(
        self,
        *,
        body: Any,
    ) -> Any:
        """Add a CLI endpoint profile.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(ops.BUILDERS["createCliEndpointProfile"](body=body))
        return payload

    async def create_http_endpoint_profile(
        self,
        *,
        body: Any,
    ) -> Any:
        """Add an HTTP endpoint profile.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(ops.BUILDERS["createHttpEndpointProfile"](body=body))
        return payload

    async def create_snmp_endpoint_profile(
        self,
        *,
        body: Any,
    ) -> Any:
        """Add an SNMP endpoint profile.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(ops.BUILDERS["createSnmpEndpointProfile"](body=body))
        return payload

    async def delete_endpoint_profile(
        self,
        *,
        profile_id: str,
    ) -> Any:
        """Delete an endpoint profile.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteEndpointProfile"](profile_id=profile_id)
        )
        return payload

    async def get_endpoint_profile(
        self,
        *,
        profile_id: str,
    ) -> Any:
        """Get an endpoint profile.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(ops.BUILDERS["getEndpointProfile"](profile_id=profile_id))
        return payload

    async def get_endpoint_profiles(
        self,
    ) -> models.EndpointProfiles:
        """Get all endpoint profiles.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(ops.BUILDERS["getEndpointProfiles"]())
        return models.EndpointProfiles.model_validate(payload or {})

    async def update_cli_endpoint_profile(
        self,
        *,
        profile_id: str,
        body: Any,
    ) -> Any:
        """Update a CLI endpoint profile.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateCliEndpointProfile"](profile_id=profile_id, body=body)
        )
        return payload

    async def update_http_endpoint_profile(
        self,
        *,
        profile_id: str,
        body: Any,
    ) -> Any:
        """Update an HTTP endpoint profile.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateHttpEndpointProfile"](profile_id=profile_id, body=body)
        )
        return payload

    async def update_snmp_endpoint_profile(
        self,
        *,
        profile_id: str,
        body: Any,
    ) -> Any:
        """Update an SNMP endpoint profile.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateSnmpEndpointProfile"](profile_id=profile_id, body=body)
        )
        return payload
