"""Internet Node.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncInternetNodeService"]


class AsyncInternetNodeService(AsyncService):
    """Internet Node."""

    async def add_internet_node_connection(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add a connection to the internet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["addInternetNodeConnection"](
                network_id=self._network(network_id), body=body
            )
        )
        return payload

    async def backdate_internet_node(
        self,
        *,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> Any:
        """Apply recent internet node changes to an existing snapshot.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["backdateInternetNode"](
                network_id=self._network(network_id), snapshot_id=self._snapshot(snapshot_id)
            )
        )
        return payload

    async def compute_internet_node_connections(
        self,
        *,
        query_id: str,
        network_id: str | None = None,
    ) -> models.L3DynamicConnectionsComputeResult:
        """Preview the connections an NQE query would produce.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["computeInternetNodeConnections"](
                network_id=self._network(network_id), query_id=query_id
            )
        )
        return models.L3DynamicConnectionsComputeResult.model_validate(payload or {})

    async def delete_internet_node_connections(
        self,
        *,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Remove internet node connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteInternetNodeConnections"](
                network_id=self._network(network_id),
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    async def get_internet_connection_suggestions(
        self,
        *,
        network_id: str | None = None,
    ) -> models.InternetConnectionSuggestions:
        """Interfaces that look like internet uplinks in the latest processed snapshot.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getInternetConnectionSuggestions"](network_id=self._network(network_id))
        )
        return models.InternetConnectionSuggestions.model_validate(payload or {})

    async def get_internet_node(
        self,
        *,
        network_id: str | None = None,
    ) -> models.InternetNode:
        """Get the network's internet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getInternetNode"](network_id=self._network(network_id))
        )
        return models.InternetNode.model_validate(payload or {})

    async def get_internet_node_connections(
        self,
        *,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Get the internet node's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getInternetNodeConnections"](
                network_id=self._network(network_id),
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    async def put_internet_node(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace the network's internet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putInternetNode"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def update_internet_node(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.InternetNode:
        """Update the network's internet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateInternetNode"](network_id=self._network(network_id), body=body)
        )
        return models.InternetNode.model_validate(payload or {})
