"""Intranet Nodes.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncIntranetNodesService"]


class AsyncIntranetNodesService(AsyncService):
    """Intranet Nodes."""

    async def add_intranet_node_connection(
        self,
        *,
        node_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add a connection to an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["addIntranetNodeConnection"](
                network_id=self._network(network_id), node_name=node_name, body=body
            )
        )
        return payload

    async def delete_intranet_node(
        self,
        *,
        node_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Remove an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteIntranetNode"](
                network_id=self._network(network_id), node_name=node_name
            )
        )
        return payload

    async def delete_intranet_node_connections(
        self,
        *,
        node_name: str,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Remove an intranet node's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteIntranetNodeConnections"](
                network_id=self._network(network_id),
                node_name=node_name,
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    async def get_intranet_node(
        self,
        *,
        node_name: str,
        network_id: str | None = None,
    ) -> models.IntranetNode:
        """Get an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getIntranetNode"](
                network_id=self._network(network_id), node_name=node_name
            )
        )
        return models.IntranetNode.model_validate(payload or {})

    async def get_intranet_node_connections(
        self,
        *,
        node_name: str,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Get an intranet node's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getIntranetNodeConnections"](
                network_id=self._network(network_id),
                node_name=node_name,
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    async def get_intranet_nodes(
        self,
        *,
        network_id: str | None = None,
    ) -> models.IntranetNodeList:
        """Get a network's intranet nodes.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getIntranetNodes"](network_id=self._network(network_id))
        )
        return models.IntranetNodeList.model_validate(payload or {})

    async def patch_intranet_node(
        self,
        *,
        node_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.IntranetNode:
        """Update an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchIntranetNode"](
                network_id=self._network(network_id), node_name=node_name, body=body
            )
        )
        return models.IntranetNode.model_validate(payload or {})

    async def put_intranet_node(
        self,
        *,
        node_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add or replace an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putIntranetNode"](
                network_id=self._network(network_id), node_name=node_name, body=body
            )
        )
        return payload

    async def put_intranet_nodes(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace all of a network's intranet nodes.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putIntranetNodes"](network_id=self._network(network_id), body=body)
        )
        return payload
