"""Jump Servers.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncJumpServersService"]


class AsyncJumpServersService(AsyncService):
    """Jump Servers.

    May be unavailable on your instance (admin); see docs/gating.md.
    """

    async def create_jump_server(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.JumpServer:
        """Create a jump server.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(
            ops.BUILDERS["createJumpServer"](network_id=self._network(network_id), body=body)
        )
        return models.JumpServer.model_validate(payload or {})

    async def delete_jump_server(
        self,
        *,
        jump_server_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a jump server.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteJumpServer"](
                network_id=self._network(network_id), jump_server_id=jump_server_id
            )
        )
        return payload

    async def edit_jump_server(
        self,
        *,
        jump_server_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Update a jump server.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(
            ops.BUILDERS["editJumpServer"](
                network_id=self._network(network_id), jump_server_id=jump_server_id, body=body
            )
        )
        return payload

    async def get_jump_servers(
        self,
        *,
        network_id: str | None = None,
    ) -> list[models.StoredJumpServer]:
        """Get all jump servers.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = await self._send_json(
            ops.BUILDERS["getJumpServers"](network_id=self._network(network_id))
        )
        return [models.StoredJumpServer.model_validate(row) for row in payload or []]
