"""L2VPNs.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncL2vpnsService"]


class AsyncL2vpnsService(AsyncService):
    """L2VPNs."""

    async def add_l2_vpn_connection(
        self,
        *,
        l2_vpn_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add a connection to an L2VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["addL2VpnConnection"](
                network_id=self._network(network_id), l2_vpn_name=l2_vpn_name, body=body
            )
        )
        return payload

    async def delete_l2_vpn(
        self,
        *,
        l2_vpn_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Remove an L2VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteL2Vpn"](
                network_id=self._network(network_id), l2_vpn_name=l2_vpn_name
            )
        )
        return payload

    async def delete_l2_vpn_connections(
        self,
        *,
        l2_vpn_name: str,
        network_id: str | None = None,
        device: str | None = None,
        port: str | None = None,
        vlan: str | None = None,
    ) -> models.L2VpnConnections:
        """Remove an L2VPN's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteL2VpnConnections"](
                network_id=self._network(network_id),
                l2_vpn_name=l2_vpn_name,
                device=device,
                port=port,
                vlan=vlan,
            )
        )
        return models.L2VpnConnections.model_validate(payload or {})

    async def get_l2_vpn(
        self,
        *,
        l2_vpn_name: str,
        network_id: str | None = None,
    ) -> models.L2Vpn:
        """Get an L2VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getL2Vpn"](network_id=self._network(network_id), l2_vpn_name=l2_vpn_name)
        )
        return models.L2Vpn.model_validate(payload or {})

    async def get_l2_vpn_connections(
        self,
        *,
        l2_vpn_name: str,
        network_id: str | None = None,
        device: str | None = None,
        port: str | None = None,
        vlan: str | None = None,
    ) -> models.L2VpnConnections:
        """Get an L2VPN's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getL2VpnConnections"](
                network_id=self._network(network_id),
                l2_vpn_name=l2_vpn_name,
                device=device,
                port=port,
                vlan=vlan,
            )
        )
        return models.L2VpnConnections.model_validate(payload or {})

    async def get_l2_vpns(
        self,
        *,
        network_id: str | None = None,
    ) -> models.L2VpnList:
        """Get a network's L2VPNs.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getL2Vpns"](network_id=self._network(network_id))
        )
        return models.L2VpnList.model_validate(payload or {})

    async def patch_l2_vpn(
        self,
        *,
        l2_vpn_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.L2Vpn:
        """Update an L2VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchL2Vpn"](
                network_id=self._network(network_id), l2_vpn_name=l2_vpn_name, body=body
            )
        )
        return models.L2Vpn.model_validate(payload or {})

    async def put_l2_vpn(
        self,
        *,
        l2_vpn_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add or replace an L2VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putL2Vpn"](
                network_id=self._network(network_id), l2_vpn_name=l2_vpn_name, body=body
            )
        )
        return payload

    async def put_l2_vpns(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace all of a network's L2VPNs.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putL2Vpns"](network_id=self._network(network_id), body=body)
        )
        return payload
