"""L3VPNs.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncL3vpnsService"]


class AsyncL3vpnsService(AsyncService):
    """L3VPNs."""

    async def add_l3_vpn_connection(
        self,
        *,
        l3_vpn_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add a connection to an L3VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["addL3VpnConnection"](
                network_id=self._network(network_id), l3_vpn_name=l3_vpn_name, body=body
            )
        )
        return payload

    async def delete_l3_vpn(
        self,
        *,
        l3_vpn_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Remove an L3VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteL3Vpn"](
                network_id=self._network(network_id), l3_vpn_name=l3_vpn_name
            )
        )
        return payload

    async def delete_l3_vpn_connections(
        self,
        *,
        l3_vpn_name: str,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Remove an L3VPN's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteL3VpnConnections"](
                network_id=self._network(network_id),
                l3_vpn_name=l3_vpn_name,
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    async def get_l3_vpn(
        self,
        *,
        l3_vpn_name: str,
        network_id: str | None = None,
    ) -> models.L3Vpn:
        """Get an L3VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getL3Vpn"](network_id=self._network(network_id), l3_vpn_name=l3_vpn_name)
        )
        return models.L3Vpn.model_validate(payload or {})

    async def get_l3_vpn_connections(
        self,
        *,
        l3_vpn_name: str,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Get an L3VPN's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getL3VpnConnections"](
                network_id=self._network(network_id),
                l3_vpn_name=l3_vpn_name,
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    async def get_l3_vpns(
        self,
        *,
        network_id: str | None = None,
    ) -> models.L3VpnList:
        """Get a network's L3VPNs.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getL3Vpns"](network_id=self._network(network_id))
        )
        return models.L3VpnList.model_validate(payload or {})

    async def patch_l3_vpn(
        self,
        *,
        l3_vpn_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.L3Vpn:
        """Update an L3VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchL3Vpn"](
                network_id=self._network(network_id), l3_vpn_name=l3_vpn_name, body=body
            )
        )
        return models.L3Vpn.model_validate(payload or {})

    async def put_l3_vpn(
        self,
        *,
        l3_vpn_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add or replace an L3VPN.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putL3Vpn"](
                network_id=self._network(network_id), l3_vpn_name=l3_vpn_name, body=body
            )
        )
        return payload

    async def put_l3_vpns(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace all of a network's L3VPNs.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putL3Vpns"](network_id=self._network(network_id), body=body)
        )
        return payload
