"""Network Endpoints.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncNetworkEndpointsService"]


class AsyncNetworkEndpointsService(AsyncService):
    """Network Endpoints."""

    async def create_cli_network_endpoint(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.CliNetworkEndpoint:
        """Add a CLI network endpoint.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["createCliNetworkEndpoint"](
                network_id=self._network(network_id), body=body
            )
        )
        return models.CliNetworkEndpoint.model_validate(payload or {})

    async def create_cli_network_endpoints(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add CLI network endpoints.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["createCliNetworkEndpoints"](
                network_id=self._network(network_id), body=body
            )
        )
        return payload

    async def create_http_network_endpoint(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.HttpNetworkEndpoint:
        """Add an HTTP network endpoint.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["createHttpNetworkEndpoint"](
                network_id=self._network(network_id), body=body
            )
        )
        return models.HttpNetworkEndpoint.model_validate(payload or {})

    async def create_http_network_endpoints(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add HTTP network endpoints.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["createHttpNetworkEndpoints"](
                network_id=self._network(network_id), body=body
            )
        )
        return payload

    async def create_snmp_network_endpoint(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.SnmpNetworkEndpoint:
        """Add an SNMP network endpoint.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["createSnmpNetworkEndpoint"](
                network_id=self._network(network_id), body=body
            )
        )
        return models.SnmpNetworkEndpoint.model_validate(payload or {})

    async def create_snmp_network_endpoints(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add SNMP network endpoints.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["createSnmpNetworkEndpoints"](
                network_id=self._network(network_id), body=body
            )
        )
        return payload

    async def delete_network_endpoint(
        self,
        *,
        endpoint_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a network endpoint.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteNetworkEndpoint"](
                network_id=self._network(network_id), endpoint_name=endpoint_name
            )
        )
        return payload

    async def delete_network_endpoints(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Delete specific network endpoints.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteNetworkEndpoints"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def get_network_endpoint(
        self,
        *,
        endpoint_name: str,
        network_id: str | None = None,
        with_: Sequence[str] | None = None,
    ) -> Any:
        """Get a network endpoint.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getNetworkEndpoint"](
                network_id=self._network(network_id), endpoint_name=endpoint_name, with_=with_
            )
        )
        return payload

    async def get_network_endpoints(
        self,
        *,
        network_id: str | None = None,
        with_: Sequence[str] | None = None,
    ) -> models.NetworkEndpoints:
        """Get a network's endpoints.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getNetworkEndpoints"](network_id=self._network(network_id), with_=with_)
        )
        return models.NetworkEndpoints.model_validate(payload or {})

    async def patch_network_endpoints(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Update specific network endpoints.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchNetworkEndpoints"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def update_cli_network_endpoint(
        self,
        *,
        endpoint_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.CliNetworkEndpoint:
        """Update a CLI network endpoint.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateCliNetworkEndpoint"](
                network_id=self._network(network_id), endpoint_name=endpoint_name, body=body
            )
        )
        return models.CliNetworkEndpoint.model_validate(payload or {})

    async def update_http_network_endpoint(
        self,
        *,
        endpoint_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.HttpNetworkEndpoint:
        """Update an HTTP network endpoint.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateHttpNetworkEndpoint"](
                network_id=self._network(network_id), endpoint_name=endpoint_name, body=body
            )
        )
        return models.HttpNetworkEndpoint.model_validate(payload or {})

    async def update_snmp_network_endpoint(
        self,
        *,
        endpoint_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.SnmpNetworkEndpoint:
        """Update an SNMP network endpoint.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateSnmpNetworkEndpoint"](
                network_id=self._network(network_id), endpoint_name=endpoint_name, body=body
            )
        )
        return models.SnmpNetworkEndpoint.model_validate(payload or {})
