"""Network Locations.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncNetworkLocationsService"]


class AsyncNetworkLocationsService(AsyncService):
    """Network Locations."""

    async def add_device_cluster(
        self,
        *,
        location_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Create a device cluster at a location.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["addDeviceCluster"](
                network_id=self._network(network_id), location_id=location_id, body=body
            )
        )
        return payload

    async def add_location(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.Location:
        """Create a network location.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["addLocation"](network_id=self._network(network_id), body=body)
        )
        return models.Location.model_validate(payload or {})

    async def delete_device_cluster(
        self,
        *,
        location_id: str,
        cluster_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a device cluster.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteDeviceCluster"](
                network_id=self._network(network_id),
                location_id=location_id,
                cluster_name=cluster_name,
            )
        )
        return payload

    async def delete_location(
        self,
        *,
        location_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a network location.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteLocation"](
                network_id=self._network(network_id), location_id=location_id
            )
        )
        return payload

    async def get_atlas(
        self,
        *,
        network_id: str | None = None,
    ) -> Any:
        """Get device locations.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getAtlas"](network_id=self._network(network_id))
        )
        return payload

    async def get_device_cluster(
        self,
        *,
        location_id: str,
        cluster_name: str,
        network_id: str | None = None,
    ) -> models.DeviceCluster:
        """Get a device cluster.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getDeviceCluster"](
                network_id=self._network(network_id),
                location_id=location_id,
                cluster_name=cluster_name,
            )
        )
        return models.DeviceCluster.model_validate(payload or {})

    async def get_device_clusters(
        self,
        *,
        location_id: str,
        network_id: str | None = None,
    ) -> list[models.DeviceCluster]:
        """Get the device clusters at a location.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getDeviceClusters"](
                network_id=self._network(network_id), location_id=location_id
            )
        )
        return [models.DeviceCluster.model_validate(row) for row in payload or []]

    async def get_location(
        self,
        *,
        location_id: str,
        network_id: str | None = None,
    ) -> models.Location:
        """Get a network location.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getLocation"](
                network_id=self._network(network_id), location_id=location_id
            )
        )
        return models.Location.model_validate(payload or {})

    async def get_locations(
        self,
        *,
        network_id: str | None = None,
    ) -> list[models.Location]:
        """Get a network's locations.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getLocations"](network_id=self._network(network_id))
        )
        return [models.Location.model_validate(row) for row in payload or []]

    async def patch_location(
        self,
        *,
        location_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.Location:
        """Update a network location.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchLocation"](
                network_id=self._network(network_id), location_id=location_id, body=body
            )
        )
        return models.Location.model_validate(payload or {})

    async def patch_locations(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Create or update network locations.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchLocations"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def put_device_clusters(
        self,
        *,
        location_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace all device clusters at a location.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putDeviceClusters"](
                network_id=self._network(network_id), location_id=location_id, body=body
            )
        )
        return payload

    async def put_locations(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Create network locations.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putLocations"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def update_atlas(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Update device locations.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateAtlas"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def update_device_cluster(
        self,
        *,
        location_id: str,
        cluster_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Update a device cluster.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateDeviceCluster"](
                network_id=self._network(network_id),
                location_id=location_id,
                cluster_name=cluster_name,
                body=body,
            )
        )
        return payload
