"""Network Topology.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

import warnings
from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncNetworkTopologyService"]


class AsyncNetworkTopologyService(AsyncService):
    """Network Topology."""

    async def backdate_link_overrides(
        self,
        *,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> Any:
        """Apply recent link override changes.

        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["backdateLinkOverrides"](
                network_id=self._network(network_id), snapshot_id=self._snapshot(snapshot_id)
            )
        )
        return payload

    async def edit_snapshot_link_overrides(
        self,
        *,
        snapshot_id: str,
        body: Any,
    ) -> Any:
        """Edit link overrides at a Snapshot.

        Deprecated by Forward.
        """
        warnings.warn(
            "editSnapshotLinkOverrides is deprecated in the Forward API",
            DeprecationWarning,
            stacklevel=2,
        )
        payload = await self._send_json(
            ops.BUILDERS["editSnapshotLinkOverrides"](snapshot_id=snapshot_id, body=body)
        )
        return payload

    async def get_link_overrides(
        self,
        *,
        network_id: str | None = None,
    ) -> models.LinkOverrides:
        """Get the network's link overrides.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getLinkOverrides"](network_id=self._network(network_id))
        )
        return models.LinkOverrides.model_validate(payload or {})

    async def get_link_overrides_at_snapshot(
        self,
        *,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.LinkOverrides:
        """Get a Snapshot's link overrides.

        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getLinkOverridesAtSnapshot"](
                network_id=self._network(network_id), snapshot_id=self._snapshot(snapshot_id)
            )
        )
        return models.LinkOverrides.model_validate(payload or {})

    async def get_recent_link_override_changes(
        self,
        *,
        network_id: str | None = None,
    ) -> models.LinkOverridesEdit:
        """Get recent link override changes.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getRecentLinkOverrideChanges"](network_id=self._network(network_id))
        )
        return models.LinkOverridesEdit.model_validate(payload or {})

    async def get_snapshot_link_overrides(
        self,
        *,
        snapshot_id: str,
    ) -> models.LinkOverrides:
        """Get link overrides for a Snapshot.

        Deprecated by Forward.
        """
        warnings.warn(
            "getSnapshotLinkOverrides is deprecated in the Forward API",
            DeprecationWarning,
            stacklevel=2,
        )
        payload = await self._send_json(
            ops.BUILDERS["getSnapshotLinkOverrides"](snapshot_id=snapshot_id)
        )
        return models.LinkOverrides.model_validate(payload or {})

    async def get_topology(
        self,
        *,
        snapshot_id: str,
    ) -> list[models.TopologyLink]:
        """Get the network topology."""
        payload = await self._send_json(ops.BUILDERS["getTopology"](snapshot_id=snapshot_id))
        return [models.TopologyLink.model_validate(row) for row in payload or []]

    async def patch_link_overrides(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Edit the network's link overrides.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchLinkOverrides"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def put_link_overrides(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Set the network's link overrides.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putLinkOverrides"](network_id=self._network(network_id), body=body)
        )
        return payload

    async def replace_snapshot_link_overrides(
        self,
        *,
        snapshot_id: str,
        body: Any,
    ) -> Any:
        """Replace link overrides at a Snapshot.

        Deprecated by Forward.
        """
        warnings.warn(
            "replaceSnapshotLinkOverrides is deprecated in the Forward API",
            DeprecationWarning,
            stacklevel=2,
        )
        payload = await self._send_json(
            ops.BUILDERS["replaceSnapshotLinkOverrides"](snapshot_id=snapshot_id, body=body)
        )
        return payload
