"""Path Search.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncPathSearchService"]


class AsyncPathSearchService(AsyncService):
    """Path Search."""

    async def get_l7_applications(
        self,
    ) -> list[models.L7Application]:
        """List known L7 applications."""
        payload = await self._send_json(ops.BUILDERS["getL7Applications"]())
        return [models.L7Application.model_validate(row) for row in payload or []]

    async def get_paths(
        self,
        *,
        dst_ip: str,
        network_id: str | None = None,
        from_: str | None = None,
        src_ip: str | None = None,
        intent: str | None = None,
        ip_proto: int | None = None,
        src_port: str | None = None,
        dst_port: str | None = None,
        icmp_type: int | None = None,
        fin: int | None = None,
        syn: int | None = None,
        rst: int | None = None,
        psh: int | None = None,
        ack: int | None = None,
        urg: int | None = None,
        app_id: str | None = None,
        user_id: str | None = None,
        user_group_id: str | None = None,
        url: str | None = None,
        domain: str | None = None,
        include_tags: bool | None = None,
        include_network_functions: bool | None = None,
        max_candidates: int | None = None,
        max_results: int | None = None,
        max_return_path_results: int | None = None,
        max_seconds: int | None = None,
        snapshot_id: str | None = None,
    ) -> models.PathSearchResponse:
        """Trace packets through the network.

        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getPaths"](
                network_id=self._network(network_id),
                from_=from_,
                src_ip=src_ip,
                dst_ip=dst_ip,
                intent=intent,
                ip_proto=ip_proto,
                src_port=src_port,
                dst_port=dst_port,
                icmp_type=icmp_type,
                fin=fin,
                syn=syn,
                rst=rst,
                psh=psh,
                ack=ack,
                urg=urg,
                app_id=app_id,
                user_id=user_id,
                user_group_id=user_group_id,
                url=url,
                domain=domain,
                include_tags=include_tags,
                include_network_functions=include_network_functions,
                max_candidates=max_candidates,
                max_results=max_results,
                max_return_path_results=max_return_path_results,
                max_seconds=max_seconds,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return models.PathSearchResponse.model_validate(payload or {})

    async def get_paths_bulk(
        self,
        *,
        body: Any,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> list[models.PathSearchResponse]:
        """Trace sets of packets through the network.

        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getPathsBulk"](
                network_id=self._network(network_id),
                body=body,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return [models.PathSearchResponse.model_validate(row) for row in payload or []]

    async def get_paths_bulk_seq(
        self,
        *,
        body: Any,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> AsyncIterator[bytes]:
        """Trace sets of packets through the network (streaming).

        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        async with self._transport.stream(
            ops.BUILDERS["getPathsBulkSeq"](
                network_id=self._network(network_id),
                body=body,
                snapshot_id=self._snapshot(snapshot_id),
            )
        ) as response:
            async for chunk in response.aiter_bytes():
                yield chunk
