"""Security Zones.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncSecurityZonesService"]


class AsyncSecurityZonesService(AsyncService):
    """Security Zones."""

    async def get_security_zone(
        self,
        *,
        device_name: str,
        zone_name: str,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.SecurityZoneDetails:
        """One device zone's VRFs, interfaces, subnets and covered topology.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getSecurityZone"](
                network_id=self._network(network_id),
                device_name=device_name,
                zone_name=zone_name,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return models.SecurityZoneDetails.model_validate(payload or {})

    async def get_security_zones(
        self,
        *,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.SecurityZones:
        """Every device's security zones.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getSecurityZones"](
                network_id=self._network(network_id), snapshot_id=self._snapshot(snapshot_id)
            )
        )
        return models.SecurityZones.model_validate(payload or {})
