"""Security Matrix.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncSecurityMatrixService"]


class AsyncSecurityMatrixService(AsyncService):
    """Security Matrix."""

    async def get_anonymous_security_matrix(
        self,
        *,
        body: Any,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.SecurityMatrixResult:
        """Run the security matrix for resource pools without saving a filter.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getAnonymousSecurityMatrix"](
                network_id=self._network(network_id),
                body=body,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return models.SecurityMatrixResult.model_validate(payload or {})

    async def get_security_matrix(
        self,
        *,
        filter_id: str,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.SecurityMatrixResult:
        """Run the security matrix for a saved filter.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getSecurityMatrix"](
                network_id=self._network(network_id),
                filter_id=filter_id,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return models.SecurityMatrixResult.model_validate(payload or {})
