"""Snapshot Diffs.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncSnapshotDiffsService"]


class AsyncSnapshotDiffsService(AsyncService):
    """Snapshot Diffs."""

    async def get_routing_loop_diff_count(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.RoutingLoopDiffCount:
        """How many routing loops the change introduces.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["getRoutingLoopDiffCount"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.RoutingLoopDiffCount.model_validate(payload or {})

    async def get_subnet_connectivity_diff(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.SubnetConnectivityDiff:
        """How site-to-site connectivity changed between two snapshots.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["getSubnetConnectivityDiff"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.SubnetConnectivityDiff.model_validate(payload or {})

    async def get_vulnerability_diff_counts(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.VulnerabilityDiffCounts:
        """How vulnerability exposure changed between two snapshots.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["getVulnerabilityDiffCounts"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.VulnerabilityDiffCounts.model_validate(payload or {})
