"""System Administration.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._ops import rest as ops

__all__ = ["AsyncSystemAdministrationService"]


class AsyncSystemAdministrationService(AsyncService):
    """System Administration.

    May be unavailable on your instance (admin, deployment, license); see docs/gating.md.
    """

    async def get_cve_index(
        self,
    ) -> AsyncIterator[bytes]:
        """Export the CVE index.

        May be unavailable (license, deployment, admin); see docs/gating.md.
        """
        async with self._transport.stream(ops.BUILDERS["getCveIndex"]()) as response:
            async for chunk in response.aiter_bytes():
                yield chunk

    async def put_cve_index(
        self,
        *,
        body: Any,
        sha: str | None = None,
    ) -> Any:
        """Import a new CVE index.

        May be unavailable (license, deployment, admin); see docs/gating.md.
        """
        payload = await self._send_json(ops.BUILDERS["putCveIndex"](body=body, sha=sha))
        return payload
