"""WAN Circuits.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncWANCircuitsService"]


class AsyncWANCircuitsService(AsyncService):
    """WAN Circuits."""

    async def backdate_wan_circuits(
        self,
        *,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> Any:
        """Apply recent WAN circuit changes to an existing snapshot.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["backdateWanCircuits"](
                network_id=self._network(network_id), snapshot_id=self._snapshot(snapshot_id)
            )
        )
        return payload

    async def delete_wan_circuit(
        self,
        *,
        wan_circuit_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Remove a WAN circuit.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["deleteWanCircuit"](
                network_id=self._network(network_id), wan_circuit_name=wan_circuit_name
            )
        )
        return payload

    async def get_wan_circuit(
        self,
        *,
        wan_circuit_name: str,
        network_id: str | None = None,
    ) -> models.WanCircuit:
        """Get a WAN circuit.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getWanCircuit"](
                network_id=self._network(network_id), wan_circuit_name=wan_circuit_name
            )
        )
        return models.WanCircuit.model_validate(payload or {})

    async def get_wan_circuits(
        self,
        *,
        network_id: str | None = None,
    ) -> models.WanCircuitList:
        """Get a network's WAN circuits.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["getWanCircuits"](network_id=self._network(network_id))
        )
        return models.WanCircuitList.model_validate(payload or {})

    async def patch_wan_circuit(
        self,
        *,
        wan_circuit_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.WanCircuit:
        """Update a WAN circuit.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["patchWanCircuit"](
                network_id=self._network(network_id), wan_circuit_name=wan_circuit_name, body=body
            )
        )
        return models.WanCircuit.model_validate(payload or {})

    async def put_wan_circuit(
        self,
        *,
        wan_circuit_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add or replace a WAN circuit.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putWanCircuit"](
                network_id=self._network(network_id), wan_circuit_name=wan_circuit_name, body=body
            )
        )
        return payload

    async def put_wan_circuits(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace all of a network's WAN circuits.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = await self._send_json(
            ops.BUILDERS["putWanCircuits"](network_id=self._network(network_id), body=body)
        )
        return payload
