"""Webhooks.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["AsyncWebhooksService"]


class AsyncWebhooksService(AsyncService):
    """Webhooks."""

    async def create_webhook(
        self,
        *,
        body: Any,
    ) -> Any:
        """Create a webhook.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["createWebhook"](body=body))
        return payload

    async def delete_webhook(
        self,
        *,
        webhook_name: str,
    ) -> Any:
        """Delete a webhook.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["deleteWebhook"](webhook_name=webhook_name))
        return payload

    async def get_webhook_default_templates(
        self,
        *,
        event_type: str,
    ) -> list[models.WebhookTemplate]:
        """The default payload templates for an event type.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["getWebhookDefaultTemplates"](event_type=event_type)
        )
        return [models.WebhookTemplate.model_validate(row) for row in payload or []]

    async def list_webhooks(
        self,
    ) -> models.WebhooksAndTestResults:
        """The org's webhooks and their last test results.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["listWebhooks"]())
        return models.WebhooksAndTestResults.model_validate(payload or {})

    async def test_webhook(
        self,
        *,
        webhook_name: str,
    ) -> models.WebhookTestResult:
        """Send a test event to a saved webhook.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["testWebhook"](webhook_name=webhook_name))
        return models.WebhookTestResult.model_validate(payload or {})

    async def test_webhook_definition(
        self,
        *,
        body: Any,
    ) -> models.WebhookTestResult:
        """Send a test event to a webhook definition without saving it.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(ops.BUILDERS["testWebhookDefinition"](body=body))
        return models.WebhookTestResult.model_validate(payload or {})

    async def update_webhook(
        self,
        *,
        webhook_name: str,
        body: Any,
    ) -> Any:
        """Change a webhook.

        Unpublished: not part of Forward's documented API.
        """
        payload = await self._send_json(
            ops.BUILDERS["updateWebhook"](webhook_name=webhook_name, body=body)
        )
        return payload
