"""Enum member names as NQE defines them.

Generated by scripts/gen_nqe_enums.py -- do not edit.

These are **not** the models in :mod:`forward_sdk.models`. Those describe
Forward's REST schema; NQE is a separate namespace that disagrees about both
type names and member names. Use these when building a query predicate, and the
models when reading a response back.

    >>> from forward_sdk.nqe.enums import members
    >>> "AZURE" in members("Vendor")
    True
    >>> "MICROSOFT" in members("Vendor")   # a REST name; NQE rejects it
    False
"""

from __future__ import annotations

from difflib import get_close_matches

__all__ = ["NQE_ENUMS", "members", "suggest"]


#: NQE type name to the members NQE accepts for it.
NQE_ENUMS: dict[str, frozenset[str]] = {
    "AclAction": frozenset(
        {
            "DENY",
            "EVALUATE",
            "PBR",
            "PERMIT",
        }
    ),
    "AdminStatus": frozenset(
        {
            "DOWN",
            "UP",
        }
    ),
    "AfiSafiType": frozenset(
        {
            "IPV4_ANY",
            "IPV4_LABELED_UNICAST",
            "IPV4_MCAST_VPN",
            "IPV4_MDT",
            "IPV4_MULTICAST",
            "IPV4_UNICAST",
            "IPV6_ANY",
            "IPV6_LABELED_UNICAST",
            "IPV6_MCAST_VPN",
            "IPV6_MDT",
            "IPV6_MULTICAST",
            "IPV6_UNICAST",
            "L2VPN_EVPN",
            "L2VPN_VPLS",
            "L3VPN_IPV4_ANY",
            "L3VPN_IPV4_MULTICAST",
            "L3VPN_IPV4_UNICAST",
            "L3VPN_IPV6_ANY",
            "L3VPN_IPV6_MULTICAST",
            "L3VPN_IPV6_UNICAST",
            "LINK_STATE",
            "NSAP_UNICAST",
            "RTFILTER_UNICAST",
            "SRTE_POLICY_IPV4",
            "SRTE_POLICY_IPV6",
        }
    ),
    "AsType": frozenset(
        {
            "AS_SEQ",
        }
    ),
    "Backend": frozenset(
        {
            "backendBucket",
            "server",
            "url",
        }
    ),
    "BgpOrigin": frozenset(
        {
            "EGP",
            "IGP",
            "INCOMPLETE",
        }
    ),
    "BgpSessionState": frozenset(
        {
            "ACTIVE",
            "CONNECT",
            "ESTABLISHED",
            "IDLE",
            "OPENCONFIRM",
            "OPENSENT",
        }
    ),
    "CloudRouteNextHop": frozenset(
        {
            "internet",
            "ipAddress",
            "local",
            "refObj",
            "unknown",
        }
    ),
    "CloudRouteType": frozenset(
        {
            "BGP",
            "STATIC",
        }
    ),
    "CloudType": frozenset(
        {
            "AWS",
            "AZURE",
            "GCP",
            "IBM",
        }
    ),
    "CommandType": frozenset(
        {
            "A10_AFLEX_RULES",
            "A10_BW_LISTS",
            "ACL_ADDRESSES",
            "ACL_CONFIG",
            "ACL_CONFIG_IPV6",
            "ACL_STATE",
            "APPLICATION_PROFILE",
            "AP_ESSID",
            "AP_SUMMARY",
            "AP_USERS",
            "ARP_TABLE",
            "ARP_VRF",
            "AVI_CLOUD",
            "AVI_SERVICE_ENGINE_GROUP",
            "AVI_VIRTUAL_SERVICE",
            "BGP_PEERS",
            "BGP_SUMMARY",
            "BLOCKED_CLIENT_IPS",
            "BLUECAT_CONFIG",
            "BLUECOAT_ADN",
            "BRIDGE_DOMAIN",
            "BRIDGE_INTERFACES",
            "BUNDLE_STATE",
            "CDP",
            "CISCO_ACI_EPM_ENDPOINTS",
            "CISCO_ACI_FABRIC_NODES",
            "CISCO_ACI_FABRIC_VRFS",
            "CISCO_ACI_NODE_TYPE",
            "CISCO_ACI_SPINE_INTERFACE_MODE",
            "CISCO_ACI_SPINE_IP_ENDPOINTS",
            "CISCO_ACI_SPINE_TUNNELS_NEXTHOP",
            "CISCO_ACI_TUNNELS_ENDPOINTS",
            "CISCO_ACI_ZONING_FILTER",
            "CISCO_ACI_ZONING_RULE",
            "CISCO_APIC_CONTROLLER_DETAIL",
            "CISCO_APIC_EXT_L3OUT_INTERFACES",
            "CISCO_APIC_SWITCH",
            "CISCO_APIC_VLAN_LEAF",
            "CISCO_APIC_VLAN_STATUS_LEAF",
            "CISCO_APIC_VPC_MAP",
            "CISCO_ASA_SHUN_TABLE",
            "CISCO_IOS_VFI_INTERFACES",
            "CISCO_IOS_VPLS_VFI_LIST",
            "CISCO_ITD",
            "CLUSTER_INTERFACES",
            "CLUSTER_STATE",
            "CONFIG",
            "CRYPTO_MAP",
            "CUSTOM",
            "DEFAULT_GATEWAYS",
            "DEVICE_HARDWARE_INFO",
            "DNS_CACHE",
            "DOMAIN_NAME",
            "EVPN",
            "F5_AFM_CONFIG",
            "F5_AFM_STATE",
            "F5_CM_MODULE_STATE",
            "F5_LTM_CONFIG",
            "F5_LTM_IRULES",
            "F5_LTM_POOL_STATE",
            "F5_VCMP_GUESTS",
            "F5_VCMP_GUESTS_ADDRS",
            "F5_VIRTUAL_SERVER_STATE",
            "FABRICPATH_TABLE",
            "FAILOVER",
            "FIREWALL_DYNAMIC_OBJECTS",
            "FIREWALL_IDENTITY_MONITOR",
            "FIREWALL_IDENTITY_ROLES",
            "FIREWALL_OBJECTS",
            "FIREWALL_POLICIES",
            "FORWARDING_MODES",
            "HAIPE_BATTERY_CHANGE_DATE",
            "HAIPE_DVROW_STATUS",
            "HAIPE_FIREFLY_EXPIRATION",
            "HAIPE_FIREFLY_NATIONAL_SHORT_TITLE",
            "HAIPE_FIREFLY_TABLE",
            "HAIPE_STATION_IDENTIFIER",
            "HAIPE_SYSTEM_DATE",
            "HAIPE_SYSTEM_UPTIME",
            "HEALTH_CHECKS_STATS",
            "HOSTNAME",
            "HSRP_STATE",
            "IFINDEX2_IPV4",
            "IFINDEX_IPV4",
            "IGMP_GROUPS",
            "IGMP_INTERFACES",
            "IGMP_VRF_GROUPS",
            "IGMP_VRF_INTERFACES",
            "INTERFACES",
            "INTERFACES_MAC",
            "INTERFACES_QUEUING_INFO",
            "INTERFACES_STATUS",
            "INTERFACES_TRUNK",
            "INTERFACES_VRF",
            "INVENTORY",
            "IPSEC_STATE",
            "IPV4_INTERFACES",
            "IPV4_MCAST_RP",
            "IPV4_VRRP_STATE",
            "IPV6_IGMP_VRF_INTERFACES",
            "IPV6_INTERFACES",
            "IPV6_MCAST_RP",
            "IPV6_VRRP_STATE",
            "IP_IGMP_SNOOP_TRACKING",
            "L2CIRCUITS_STATE",
            "L2VPN_BRIDGE_DOMAIN",
            "L2VPN_XCONNECT_STATE",
            "LICENSE_INFO",
            "LLDP",
            "MAC_TABLE",
            "MGMT_SERVICES",
            "MIB_MAC_ADDRESSES",
            "MLAG_INTERFACE_STATE",
            "MLAG_STATE",
            "MPLS_BYPASS_LSP_TUNNEL_STATE",
            "MPLS_PSEUDOWIRE_STATE",
            "MPLS_TE_TUNNELS_STATE",
            "MPLS_VIRTUAL_CIRCUIT_STATE",
            "NAT_ADDRESSES",
            "NDP_TABLE",
            "NETSCREEN_NSRP_STATE",
            "NETWORK_PROFILE",
            "NHRP_STATE",
            "OTV",
            "PACKET_FILTER_CONFIG",
            "PANOS_CONFIG_PUSHED_SHARED_POLICY",
            "PANOS_CONFIG_PUSHED_TEMPLATE",
            "PANOS_EXTERNAL_IP_LIST",
            "PARTITION_CONFIG",
            "POLICY_ORDER",
            "POLICY_TRAFFIC_SELECTORS",
            "PORT_CHANNEL_MEMBERS",
            "PORT_LABELS",
            "PORT_MIRRORING_STATE",
            "PORT_SECURITY_STATE",
            "PREDEFINED_APPS",
            "PROXY_POLICIES",
            "PROXY_SERVICES",
            "REGISTERED_IP_ADDRESSES",
            "RIVERBED_HOST_LABELS",
            "RIVERBED_IN_PATH_NEIGHBORS",
            "RIVERBED_IN_PATH_RULES",
            "RIVERBED_PATH_SELECTION_RULES",
            "RIVERBED_STEELHEAD_NEIGHBORS",
            "ROOT_CONTEXT_CONFIG",
            "ROUTING_PROTOCOL_CONFIG",
            "RSVP_SESSION_STATE",
            "SDWAN_CONFIG",
            "SDWAN_OMP_IPV6_ROUTES",
            "SDWAN_OMP_ROUTES",
            "SLA_IP_TRACKING_STATE",
            "SLB_CS_VIRTUAL_SERVERS",
            "SLB_GSLB_SERVICES",
            "SLB_GSLB_VIRTUAL_SERVERS",
            "SLB_SERVERS",
            "SLB_SERVER_DETAILS",
            "SLB_SERVICES",
            "SLB_SERVICE_GROUPS",
            "SLB_VIRTUAL_SERVERS",
            "SNMP_SYS_DESCR",
            "SNMP_SYS_NAME",
            "SNMP_TARGET_ADDRESS",
            "SSH_RSA_KEY_LENGTH",
            "STP_STATE",
            "SWITCHPORT_STATE",
            "SYSTEM_SETTINGS",
            "TUNNELS_STATUS",
            "UPTIME",
            "VERSION",
            "VIRTUAL_ADDRESSES",
            "VIRTUAL_CONTEXTS",
            "VLAN_LIST",
            "VNIC_STATE",
            "VPC_CONSISTENCY",
            "VPLS_FORWARDING",
            "VPLS_MAC_TABLE",
            "VPN_TUNNELS",
            "VRF_MCAST_ROUTING",
            "VXLAN_ESI",
            "VXLAN_MAC_TABLE",
            "VXLAN_STATE",
            "WCCP_STATE",
        }
    ),
    "ContainerType": frozenset(
        {
            "COLLECTION",
            "GROUP",
            "POLICY",
        }
    ),
    "CveFindingBasis": frozenset(
        {
            "CONFIG",
            "PLATFORM",
        }
    ),
    "DeviceCollectionError": frozenset(
        {
            "APIC_CONFIG_COLLECTION_FAILED",
            "API_SERVER_FAILED_TO_RESPOND",
            "AUTHENTICATION_FAILED",
            "AUTHORIZATION_FAILED",
            "AVI_CONTROLLER_WITHOUT_HEALTHY_SERVICE_ENGINES",
            "AVI_SHELL_AUTH_FAILED",
            "BMP_COLLECTION_FAILED",
            "BMP_COLLECTION_REFUSED",
            "BMP_COLLECTION_TIMEOUT",
            "BMP_CONFIGURED_WITH_LOCAL_IP",
            "BMP_CONNECTION_FAILED",
            "BMP_CONNECTION_TIMEOUT",
            "BMP_NOT_CONFIGURED",
            "BMP_SESSION_ALREADY_ESTABLISHED",
            "CERTIFICATE_CHECK_FAILED",
            "COLLECTION_CANCELED",
            "COLLECTION_NOT_FOUND",
            "COLLECTION_TIMED_OUT",
            "COMMAND_DISABLED",
            "CONFIG_COLLECTION_UNAUTHORIZED",
            "CONNECTION_REFUSED",
            "CONNECTION_TIMEOUT",
            "DEVICE_IN_BAD_STATE",
            "DEVICE_IS_CHILD_CONTEXT",
            "DEVICE_TYPE_UNDETECTED",
            "DUPLICATE_DEVICE",
            "EXPERT_PASSWORD_ERROR",
            "FILE_TRANSFER_FAILED",
            "INCOMPLETE_SETUP",
            "INFINITE_LOOP_IN_COMMAND_OUTPUT",
            "IO_ERROR",
            "JUMP_SERVER_CONNECTION_FAILED",
            "JUMP_SERVER_CONNECTION_TIMEOUT",
            "JUMP_SERVER_KEY_EXCHANGE_FAILED",
            "JUMP_SERVER_PASSWORD_AUTH_FAILED",
            "JUMP_SERVER_PASSWORD_EXPIRED",
            "KEY_EXCHANGE_FAILED",
            "MANAGER_COLLECTOR_NOT_FOUND",
            "MISSING_FILE",
            "NETWORK_UNREACHABLE",
            "NO_SPACE_LEFT_ON_COLLECTED_DEVICE",
            "NO_SPACE_LEFT_ON_DEVICE",
            "OPERATION_TIMED_OUT",
            "PASSWORD_EXPIRED",
            "PRIV_PASSWORD_ERROR",
            "PROJECT_VIEW_PERMISSION_MISSING",
            "PROMPT_DISCOVERY_FAILED",
            "PROXY_SERVER_AUTHENTICATION_FAILED",
            "PROXY_SERVER_CONNECTION_FAILED",
            "PROXY_SERVER_PING_FAILED",
            "PROXY_SERVER_PORT_REACHABILITY_FAILED",
            "SESSION_CLOSED",
            "SESSION_LIMIT_REACHED",
            "SLOW_READ_RATE_DETECTED",
            "SOME_OID_FAILED",
            "STATE_COLLECTION_FAILED",
            "T128_CONDUCTOR_WITHOUT_HEALTHY_ROUTERS",
            "T128_CONFIG_ABSENT",
            "TACACS_SESSION_EXPIRED",
            "TRANSIENT_SLOW_READ_RATE_DETECTED",
            "UNDISCOVERED_ACI_FABRIC",
            "UNEXPECTED_KEY_EXCHANGE_MESSAGE",
            "UNKNOWN",
            "UNRESOLVABLE_HOSTNAME",
            "UNSUPPORTED_DEVICE_TYPE",
            "UNSUPPORTED_SSL_CONNECTION",
            "UNSUPPORTED_VENDOR",
            "UNSUPPORTED_VERSION",
            "VELOS_PARTITION_WITHOUT_BLADES",
            "WARN_TYPE_MISMATCH",
        }
    ),
    "DeviceHostType": frozenset(
        {
            "CloudHost",
            "EdgeNode",
            "InferredHost",
            "Unknown",
        }
    ),
    "DevicePartType": frozenset(
        {
            "APPLICATION",
            "CHASSIS",
            "FABRIC_MODULE",
            "FAN_MODULE",
            "LINE_CARD",
            "MOTHERBOARD",
            "OTHER",
            "POWER_SUPPLY",
            "RACK",
            "ROUTING_ENGINE",
            "STACK",
            "STACK_MODULE",
            "STACK_PORT",
            "STACK_SWITCH",
            "SUPERVISOR",
            "TRANSCEIVER",
            "UNMODELED_BACKUP_DEVICE",
        }
    ),
    "DeviceProcessingError": frozenset(
        {
            "DUPLICATE",
            "LICENSE_EXHAUSTED",
            "MISSING_SIGNATURE",
            "PARSER_EXCEPTION",
            "UNLICENSED_DEPENDENCY",
            "UNSUPPORTED_DEVICE_TYPE",
            "UNSUPPORTED_VENDOR",
        }
    ),
    "DeviceSnapshotResult": frozenset(
        {
            "collectionFailed",
            "completed",
            "processingFailed",
        }
    ),
    "DeviceType": frozenset(
        {
            "CONTROLLER",
            "ENCRYPTOR",
            "FIREWALL",
            "INTERNET",
            "INTRANET",
            "L2_VPN",
            "L3_VPN",
            "LOAD_BALANCER",
            "MISSING_PEER",
            "OTHER",
            "ROUTER",
            "SD_WAN",
            "SWITCH",
            "WAN_CIRCUIT",
            "WAN_OPTIMIZER",
            "WIFI_ACCESS_POINT",
        }
    ),
    "DuplexMode": frozenset(
        {
            "FULL",
            "HALF",
        }
    ),
    "EncapsulationHeaderType": frozenset(
        {
            "GRE",
            "IPV4",
            "IPV6",
            "MPLS",
        }
    ),
    "FhrpState": frozenset(
        {
            "BACKUP",
            "MASTER",
            "OTHER",
        }
    ),
    "GlobalAcceleratorListenerEndpoint": frozenset(
        {
            "instanceId",
            "ipAddress",
            "loadBalancerId",
        }
    ),
    "GlobalAcceleratorStatus": frozenset(
        {
            "DEPLOYED",
            "IN_PROGRESS",
        }
    ),
    "HaOperationMode": frozenset(
        {
            "ACTIVE",
            "ACTIVEBACKUP",
            "BACKUP",
            "STANDALONE",
            "STANDALONE_INACTIVE",
        }
    ),
    "HttpApiEndpointStatus": frozenset(
        {
            "ERROR",
            "MAX_PAGES_REACHED",
            "OK",
            "TIMED_OUT",
        }
    ),
    "IfaceType": frozenset(
        {
            "IF_AGGREGATE",
            "IF_BRIDGE",
            "IF_ETHERNET",
            "IF_LOOPBACK",
            "IF_ROUTED_VLAN",
            "IF_SONET",
            "IF_TE_TUNNEL",
            "IF_TUNNEL_GRE4",
            "IF_TUNNEL_GRE6",
            "IF_TUNNEL_IPSEC",
            "IF_TUNNEL_IP_IN_IP",
            "IF_TUNNEL_L2_VPN",
            "IF_TUNNEL_UNKNOWN",
            "IF_TUNNEL_VXLAN",
        }
    ),
    "KeepAliveStatus": frozenset(
        {
            "ALIVE",
            "DISABLED",
            "NOT_REACHABLE",
            "SUSPENDED",
        }
    ),
    "Layer": frozenset(
        {
            "L2",
            "L3",
        }
    ),
    "MacEntrySourceType": frozenset(
        {
            "FABRIC_PATH",
            "LOCAL",
            "MPLS",
            "VXLAN",
        }
    ),
    "MacEntryType": frozenset(
        {
            "DYNAMIC",
            "STATIC",
        }
    ),
    "MulticastMode": frozenset(
        {
            "BIDIRECTIONAL",
            "DENSE",
            "SOURCE_SPECIFIC_MULTICAST",
            "SPARSE",
            "SPARSE_DENSE",
        }
    ),
    "NatType": frozenset(
        {
            "DNat",
            "Identity",
            "LB",
            "SNat",
            "TwiceNat",
        }
    ),
    "NetworkInstanceType": frozenset(
        {
            "DEFAULT_INSTANCE",
            "L3VRF",
        }
    ),
    "NextHopType": frozenset(
        {
            "ATTACHED",
            "BROADCAST",
            "DROP",
            "RECEIVE",
            "RECURSIVE",
            "REDIRECT",
            "REMOTE",
            "UNDEFINED",
            "VRF_FORWARDED",
        }
    ),
    "OS": frozenset(
        {
            "ACOS",
            "ALKIRA_CXP",
            "APIC",
            "ARISTA_EOS",
            "ARUBA_AOS_CX",
            "ARUBA_SWITCH",
            "ARUBA_WIFI",
            "ASA",
            "AVAYA",
            "AVAYA_ERS",
            "AVI_VANTAGE",
            "BLUECAT",
            "BLUECOAT",
            "BROCADE_SWITCH",
            "CHECKPOINT",
            "CHECKPOINT_MANAGER",
            "CISCO_WIRELESS",
            "CLOUD_GENIX",
            "CLOUD_GENIX_PORTAL",
            "CUMULUS",
            "DELL_OS10",
            "DELL_OS6",
            "DELL_OS9",
            "DELL_SONIC",
            "EDGE_CORE_SONIC",
            "ENCRYPTOR",
            "ENCS_NFV",
            "ESXI",
            "EXTREME_NOS",
            "F5",
            "F5_OS_HYPERVISOR",
            "FORCEPOINT",
            "FORTINET",
            "FXOS",
            "GENERAL_DYNAMICS_ENCRYPTOR",
            "HP_COMWARE",
            "HP_PROVISION",
            "HUAWEI",
            "INTERNET_SERVICE",
            "INTRANET_SERVICE",
            "IOS",
            "IOS_XE",
            "IOS_XR",
            "JUNOS",
            "L2_VPN_SERVICE",
            "LINUX",
            "LINUX_OVS_OFCTL",
            "MERAKI_MR",
            "MERAKI_MS",
            "MERAKI_MX",
            "MIST_AP",
            "MPLS_VPN_SERVICE",
            "NETSCALER",
            "NETSCREEN",
            "NOKIA",
            "NXOS",
            "OTHER",
            "PAN_OS",
            "PENSANDO",
            "PICA8_OVS_OFCTL",
            "SG",
            "SILVER_PEAK",
            "SILVER_PEAK_ORCHESTRATOR",
            "SRX",
            "T128",
            "T128_CONDUCTOR",
            "UNKNOWN",
            "VELOCLOUD_EDGE",
            "VELOCLOUD_GATEWAY",
            "VERSA",
            "VIASAT_ENCRYPTOR",
            "VIPTELA",
            "ZSCALER_APP_CONNECTOR",
            "ZSCALER_ZPA",
        }
    ),
    "OidCollectionStatus": frozenset(
        {
            "error",
            "ok",
        }
    ),
    "OperStatus": frozenset(
        {
            "DORMANT",
            "DOWN",
            "LOWER_LAYER_DOWN",
            "NOT_PRESENT",
            "TESTING",
            "UNKNOWN",
            "UP",
        }
    ),
    "OriginProtocol": frozenset(
        {
            "BGP",
            "DIRECT_CONNECTED",
            "EIGRP",
            "FRR",
            "IGMP",
            "ISIS",
            "LDP",
            "LOCAL_AGGREGATE",
            "ODR",
            "OMP",
            "OSPF",
            "PIM",
            "RIP",
            "RSVP",
            "STATIC",
            "UNKNOWN",
            "VPLS",
            "VPN",
        }
    ),
    "OspfAreaType": frozenset(
        {
            "BACKBONE",
            "NSSA",
            "STANDARD",
            "STUB",
            "TOTALLY_NSSA",
            "TOTALLY_STUBBY",
        }
    ),
    "OspfRole": frozenset(
        {
            "BACKUP_DESIGNATED_ROUTER",
            "DESIGNATED_ROUTER",
        }
    ),
    "OspfRouterType": frozenset(
        {
            "ABR",
            "ABR_ASBR",
            "ASBR",
        }
    ),
    "PaginatedHttpEndpointStatus": frozenset(
        {
            "ERROR",
            "MAX_PAGES_REACHED",
            "OK",
            "TIMED_OUT",
        }
    ),
    "PeerCapability": frozenset(
        {
            "BRIDGE",
            "CABLE_DEVICE",
            "OTHER",
            "REPEATER",
            "ROUTER",
            "STATION",
            "TELEPHONE",
            "WLAN_AP",
        }
    ),
    "PeerStatus": frozenset(
        {
            "ADJACENCY_OK",
            "LINK_DOWN",
            "LINK_NOT_CONFIGURED",
        }
    ),
    "PeerType": frozenset(
        {
            "EXTERNAL",
            "INTERNAL",
        }
    ),
    "PortSpeed": frozenset(
        {
            "SPEED_100GB",
            "SPEED_100MB",
            "SPEED_10GB",
            "SPEED_10MB",
            "SPEED_1GB",
            "SPEED_2500MB",
            "SPEED_25GB",
            "SPEED_40GB",
            "SPEED_50GB",
            "SPEED_5GB",
            "SPEED_UNKNOWN",
        }
    ),
    "RefObjType": frozenset(
        {
            "ADDRESS_REFERENCE",
            "AWS_OUTPOST_LGW",
            "COMP_INSTANCE",
            "DCGW",
            "IGW",
            "INTERFACE",
            "NATGW",
            "SUBNET",
            "TGW",
            "VPC",
            "VPC_ENDPOINT",
            "VPC_PEERING",
            "VPNGW",
            "VPN_CONNECTION",
        }
    ),
    "RoutingProtocolType": frozenset(
        {
            "BGP",
            "DIRECTLY_CONNECTED",
            "IGMP",
            "ISIS",
            "LOCAL_AGGREGATE",
            "OSPF",
            "OSPF3",
            "PIM",
            "STATIC",
        }
    ),
    "SecurityRuleAction": frozenset(
        {
            "DENY",
            "PERMIT",
        }
    ),
    "Severity": frozenset(
        {
            "CRITICAL",
            "HIGH",
            "LOW",
            "MEDIUM",
            "NONE",
        }
    ),
    "StigSeverity": frozenset(
        {
            "HIGH",
            "LOW",
            "MEDIUM",
        }
    ),
    "SubInterfaceVlan": frozenset(
        {
            "QINQ_ID",
            "VLAN_ID",
        }
    ),
    "TransitGatewayAttachmentType": frozenset(
        {
            "CONNECT",
            "DC",
            "TGW_PEERING",
            "VPC",
            "VPN",
        }
    ),
    "Vendor": frozenset(
        {
            "A10",
            "ALKIRA",
            "AMAZON",
            "ARISTA",
            "ARUBA",
            "AVAYA",
            "AVI_NETWORKS",
            "AZURE",
            "BLUECAT",
            "BROCADE",
            "CHECKPOINT",
            "CISCO",
            "CITRIX",
            "CUMULUS",
            "DELL",
            "EDGE_CORE",
            "EXTREME",
            "F5",
            "FORCEPOINT",
            "FORTINET",
            "FORWARD_CUSTOM",
            "GENERAL_DYNAMICS",
            "GOOGLE",
            "HP",
            "HUAWEI",
            "JUNIPER",
            "LINUX_GENERIC",
            "NOKIA",
            "PALO_ALTO_NETWORKS",
            "PENSANDO",
            "PICA8",
            "RIVERBED",
            "SILVER_PEAK",
            "SYMANTEC",
            "T128",
            "UNKNOWN",
            "VERSA",
            "VIASAT",
            "VMWARE",
            "ZSCALER",
        }
    ),
    "VlanIdOrRange": frozenset(
        {
            "ID",
            "RANGE",
        }
    ),
    "VlanIdSetOrAll": frozenset(
        {
            "ALL",
            "IDS",
        }
    ),
    "VlanModeType": frozenset(
        {
            "ACCESS",
            "TRUNK",
        }
    ),
    "VpcRole": frozenset(
        {
            "OPERATIONAL_PRIMARY",
            "OPERATIONAL_SECONDARY",
            "PRIMARY",
            "SECONDARY",
        }
    ),
}


def members(type_name: str) -> frozenset[str]:
    """The members NQE accepts for ``type_name``, or empty if it is unknown.

    Empty means the type is not in the data model at all, which is different
    from a type with no members; check ``type_name in NQE_ENUMS`` to tell them
    apart.
    """
    return NQE_ENUMS.get(type_name, frozenset())


def suggest(type_name: str, member: str, *, limit: int = 3) -> list[str]:
    """Members of ``type_name`` close to ``member``, for an error message.

    A wrong member is usually a REST name reached for by mistake, and the NQE
    equivalent is often similar enough to find this way.
    """
    return get_close_matches(member, sorted(members(type_name)), n=limit, cutoff=0.6)
