# Generated from src/forward_sdk/_async/services/_generated/__init__.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Service classes generated from the Forward API description.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from forward_sdk._sync.services._generated.aliases import AliasesService
from forward_sdk._sync.services._generated.checks import ChecksService
from forward_sdk._sync.services._generated.classic_devices import ClassicDevicesService
from forward_sdk._sync.services._generated.collection_schedules import (
    CollectionSchedulesService,
)
from forward_sdk._sync.services._generated.collector_tasks import CollectorTasksService
from forward_sdk._sync.services._generated.configuration import ConfigurationService
from forward_sdk._sync.services._generated.credentials import CredentialsService
from forward_sdk._sync.services._generated.data_connectors import DataConnectorsService
from forward_sdk._sync.services._generated.data_files import DataFilesService
from forward_sdk._sync.services._generated.encryptors import EncryptorsService
from forward_sdk._sync.services._generated.endpoint_profiles import EndpointProfilesService
from forward_sdk._sync.services._generated.firewall_predict import FirewallPredictService
from forward_sdk._sync.services._generated.internet_node import InternetNodeService
from forward_sdk._sync.services._generated.intranet_nodes import IntranetNodesService
from forward_sdk._sync.services._generated.jump_servers import JumpServersService
from forward_sdk._sync.services._generated.l2vpns import L2vpnsService
from forward_sdk._sync.services._generated.l3vpns import L3vpnsService
from forward_sdk._sync.services._generated.legacy_collection import LegacyCollectionService
from forward_sdk._sync.services._generated.network_endpoints import NetworkEndpointsService
from forward_sdk._sync.services._generated.network_locations import NetworkLocationsService
from forward_sdk._sync.services._generated.network_topology import NetworkTopologyService
from forward_sdk._sync.services._generated.path_search import PathSearchService
from forward_sdk._sync.services._generated.predict_assist import PredictAssistService
from forward_sdk._sync.services._generated.system_administration import (
    SystemAdministrationService,
)
from forward_sdk._sync.services._generated.user_accounts import UserAccountsService
from forward_sdk._sync.services._generated.vulnerability_analysis import (
    VulnerabilityAnalysisService,
)
from forward_sdk._sync.services._generated.wan_circuits import WANCircuitsService
from forward_sdk._sync.services._generated.webhooks import WebhooksService

if TYPE_CHECKING:  # pragma: no cover
    from forward_sdk._sync.transport import Transport

__all__ = [
    "AliasesService",
    "ChecksService",
    "ClassicDevicesService",
    "CollectionSchedulesService",
    "CollectorTasksService",
    "ConfigurationService",
    "CredentialsService",
    "DataConnectorsService",
    "DataFilesService",
    "EncryptorsService",
    "EndpointProfilesService",
    "FirewallPredictService",
    "GeneratedServices",
    "InternetNodeService",
    "IntranetNodesService",
    "JumpServersService",
    "L2vpnsService",
    "L3vpnsService",
    "LegacyCollectionService",
    "NetworkEndpointsService",
    "NetworkLocationsService",
    "NetworkTopologyService",
    "PathSearchService",
    "PredictAssistService",
    "SystemAdministrationService",
    "UserAccountsService",
    "VulnerabilityAnalysisService",
    "WANCircuitsService",
    "WebhooksService",
]


class GeneratedServices:
    """The API groups whose services are generated.

    Declared as attributes rather than attached dynamically so that type
    checkers and editors can see them.
    """

    aliases: AliasesService
    checks: ChecksService
    classic_devices: ClassicDevicesService
    collection_schedules: CollectionSchedulesService
    collector_tasks: CollectorTasksService
    configuration: ConfigurationService
    credentials: CredentialsService
    data_connectors: DataConnectorsService
    data_files: DataFilesService
    encryptors: EncryptorsService
    endpoint_profiles: EndpointProfilesService
    firewall_predict: FirewallPredictService
    internet_node: InternetNodeService
    intranet_nodes: IntranetNodesService
    jump_servers: JumpServersService
    l2vpns: L2vpnsService
    l3vpns: L3vpnsService
    legacy_collection: LegacyCollectionService
    network_endpoints: NetworkEndpointsService
    network_locations: NetworkLocationsService
    network_topology: NetworkTopologyService
    path_search: PathSearchService
    predict_assist: PredictAssistService
    system_administration: SystemAdministrationService
    user_accounts: UserAccountsService
    vulnerability_analysis: VulnerabilityAnalysisService
    wan_circuits: WANCircuitsService
    webhooks: WebhooksService

    def _attach_generated_services(self, transport: Transport) -> None:
        self.aliases = AliasesService(transport)
        self.checks = ChecksService(transport)
        self.classic_devices = ClassicDevicesService(transport)
        self.collection_schedules = CollectionSchedulesService(transport)
        self.collector_tasks = CollectorTasksService(transport)
        self.configuration = ConfigurationService(transport)
        self.credentials = CredentialsService(transport)
        self.data_connectors = DataConnectorsService(transport)
        self.data_files = DataFilesService(transport)
        self.encryptors = EncryptorsService(transport)
        self.endpoint_profiles = EndpointProfilesService(transport)
        self.firewall_predict = FirewallPredictService(transport)
        self.internet_node = InternetNodeService(transport)
        self.intranet_nodes = IntranetNodesService(transport)
        self.jump_servers = JumpServersService(transport)
        self.l2vpns = L2vpnsService(transport)
        self.l3vpns = L3vpnsService(transport)
        self.legacy_collection = LegacyCollectionService(transport)
        self.network_endpoints = NetworkEndpointsService(transport)
        self.network_locations = NetworkLocationsService(transport)
        self.network_topology = NetworkTopologyService(transport)
        self.path_search = PathSearchService(transport)
        self.predict_assist = PredictAssistService(transport)
        self.system_administration = SystemAdministrationService(transport)
        self.user_accounts = UserAccountsService(transport)
        self.vulnerability_analysis = VulnerabilityAnalysisService(transport)
        self.wan_circuits = WANCircuitsService(transport)
        self.webhooks = WebhooksService(transport)


#: API group name to the client attribute carrying its service.
SERVICE_TAGS: dict[str, str] = {
    "Aliases": "aliases",
    "Checks": "checks",
    "Classic Devices": "classic_devices",
    "Collection Schedules": "collection_schedules",
    "Collector Tasks": "collector_tasks",
    "Configuration": "configuration",
    "Credentials": "credentials",
    "Data Connectors": "data_connectors",
    "Data Files": "data_files",
    "Encryptors": "encryptors",
    "Endpoint Profiles": "endpoint_profiles",
    "Firewall Predict": "firewall_predict",
    "Internet Node": "internet_node",
    "Intranet Nodes": "intranet_nodes",
    "Jump Servers": "jump_servers",
    "L2VPNs": "l2vpns",
    "L3VPNs": "l3vpns",
    "Legacy Collection": "legacy_collection",
    "Network Endpoints": "network_endpoints",
    "Network Locations": "network_locations",
    "Network Topology": "network_topology",
    "Path Search": "path_search",
    "Predict Assist": "predict_assist",
    "System Administration": "system_administration",
    "User Accounts": "user_accounts",
    "Vulnerability Analysis": "vulnerability_analysis",
    "WAN Circuits": "wan_circuits",
    "Webhooks": "webhooks",
}
