# Generated from src/forward_sdk/_async/services/_generated/aliases.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Aliases.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["AliasesService"]


class AliasesService(Service):
    """Aliases."""

    def create_alias(
        self,
        *,
        snapshot_id: str,
        name: str,
        body: Any,
    ) -> models.Alias:
        """Create an Alias."""
        payload = self._send_json(
            ops.BUILDERS["createAlias"](snapshot_id=snapshot_id, name=name, body=body)
        )
        return models.Alias.model_validate(payload or {})

    def deactivate_alias(
        self,
        *,
        snapshot_id: str,
        name: str,
    ) -> models.Alias:
        """Delete an Alias."""
        payload = self._send_json(
            ops.BUILDERS["deactivateAlias"](snapshot_id=snapshot_id, name=name)
        )
        return models.Alias.model_validate(payload or {})

    def deactivate_aliases(
        self,
        *,
        snapshot_id: str,
        name: Sequence[str] | None = None,
    ) -> models.Aliases:
        """Delete Aliases."""
        payload = self._send_json(
            ops.BUILDERS["deactivateAliases"](snapshot_id=snapshot_id, name=name)
        )
        return models.Aliases.model_validate(payload or {})

    def get_all_aliases(
        self,
        *,
        snapshot_id: str,
    ) -> models.Aliases:
        """Get all Aliases."""
        payload = self._send_json(ops.BUILDERS["getAllAliases"](snapshot_id=snapshot_id))
        return models.Aliases.model_validate(payload or {})

    def get_single_alias(
        self,
        *,
        snapshot_id: str,
        name: str,
    ) -> models.AliasAndValue:
        """Get an Alias."""
        payload = self._send_json(
            ops.BUILDERS["getSingleAlias"](snapshot_id=snapshot_id, name=name)
        )
        return models.AliasAndValue.model_validate(payload or {})
