# Generated from src/forward_sdk/_async/services/_generated/bgp_advertisements.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""BGP Advertisements.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["BGPAdvertisementsService"]


class BGPAdvertisementsService(Service):
    """BGP Advertisements."""

    def add_bgp_advertisement(
        self,
        *,
        change_set_id: str,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.ChangeSetDraft:
        """Inject one BGP advertisement at a device.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["addBgpAdvertisement"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                body=body,
            )
        )
        return models.ChangeSetDraft.model_validate(payload or {})

    def add_bgp_advertisements(
        self,
        *,
        change_set_id: str,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.ChangeSetDraft:
        """Inject several BGP advertisements.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["addBgpAdvertisements"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                body=body,
            )
        )
        return models.ChangeSetDraft.model_validate(payload or {})

    def get_commit_bgp_advertisement_diffs(
        self,
        *,
        change_set_id: str,
        commit_id: str,
        device_name: str,
        network_id: str | None = None,
    ) -> list[models.BgpAdvertisementDiff]:
        """How a commit changed a device's BGP advertisements.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getCommitBgpAdvertisementDiffs"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                commit_id=commit_id,
                device_name=device_name,
            )
        )
        return [models.BgpAdvertisementDiff.model_validate(row) for row in payload or []]

    def get_draft_bgp_advertisement_diffs(
        self,
        *,
        change_set_id: str,
        device_name: str,
        network_id: str | None = None,
    ) -> list[models.BgpAdvertisementDiff]:
        """How the draft changes a device's BGP advertisements.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getDraftBgpAdvertisementDiffs"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
            )
        )
        return [models.BgpAdvertisementDiff.model_validate(row) for row in payload or []]

    def restore_bgp_advertisement(
        self,
        *,
        change_set_id: str,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Undo the change set's change to one advertisement.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["restoreBgpAdvertisement"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                body=body,
            )
        )
        return payload

    def restore_bgp_advertisements(
        self,
        *,
        change_set_id: str,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Undo the change set's changes to several advertisements.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["restoreBgpAdvertisements"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                body=body,
            )
        )
        return payload

    def withdraw_bgp_advertisement(
        self,
        *,
        change_set_id: str,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.ChangeSetDraft:
        """Withdraw one BGP advertisement.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["withdrawBgpAdvertisement"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                body=body,
            )
        )
        return models.ChangeSetDraft.model_validate(payload or {})

    def withdraw_bgp_advertisements(
        self,
        *,
        change_set_id: str,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.ChangeSetDraft:
        """Withdraw several BGP advertisements.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["withdrawBgpAdvertisements"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                body=body,
            )
        )
        return models.ChangeSetDraft.model_validate(payload or {})
