# Generated from src/forward_sdk/_async/services/_generated/blast_radius.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Blast Radius.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["BlastRadiusService"]


class BlastRadiusService(Service):
    """Blast Radius."""

    def get_blast_radius(
        self,
        *,
        body: Any,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.ConnectivityDetails:
        """Sample connectivity from one location to a set of destination subnets.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getBlastRadius"](
                network_id=self._network(network_id),
                body=body,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return models.ConnectivityDetails.model_validate(payload or {})

    def get_host_centric_blast_radius(
        self,
        *,
        body: Any,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.HostConnectivityDetails:
        """The same, broken out per destination host with vulnerability counts.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getHostCentricBlastRadius"](
                network_id=self._network(network_id),
                body=body,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return models.HostConnectivityDetails.model_validate(payload or {})

    def get_host_centric_blast_radius_report(
        self,
        *,
        body: Any,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> Iterator[bytes]:
        """The host-centric blast radius as an XLSX workbook.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        with self._transport.stream(
            ops.BUILDERS["getHostCentricBlastRadiusReport"](
                network_id=self._network(network_id),
                body=body,
                snapshot_id=self._snapshot(snapshot_id),
            )
        ) as response:
            for chunk in response.iter_bytes():
                yield chunk
