# Generated from src/forward_sdk/_async/services/_generated/change_set_directories.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Change Set Directories.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["ChangeSetDirectoriesService"]


class ChangeSetDirectoriesService(Service):
    """Change Set Directories."""

    def create_change_set_directory(
        self,
        *,
        dir_path: str,
        name: str,
        network_id: str | None = None,
    ) -> Any:
        """Create a directory inside another.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["createChangeSetDirectory"](
                network_id=self._network(network_id), dir_path=dir_path, name=name
            )
        )
        return payload

    def delete_change_set_directory(
        self,
        *,
        dir_path: str,
        network_id: str | None = None,
        retain_change_sets: bool | None = None,
    ) -> Any:
        """Delete a directory.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteChangeSetDirectory"](
                network_id=self._network(network_id),
                dir_path=dir_path,
                retain_change_sets=retain_change_sets,
            )
        )
        return payload

    def list_change_set_directories(
        self,
        *,
        network_id: str | None = None,
    ) -> models.ChangeSetDirectories:
        """Every directory and the change sets in it.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["listChangeSetDirectories"](network_id=self._network(network_id))
        )
        return models.ChangeSetDirectories.model_validate(payload or {})

    def move_change_set_directory(
        self,
        *,
        dir_path: str,
        to: str,
        network_id: str | None = None,
    ) -> Any:
        """Move a directory under another.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["moveChangeSetDirectory"](
                network_id=self._network(network_id), dir_path=dir_path, to=to
            )
        )
        return payload

    def move_change_set_to_directory(
        self,
        *,
        dir_path: str,
        change_set_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Move one change set into a directory.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["moveChangeSetToDirectory"](
                network_id=self._network(network_id), dir_path=dir_path, change_set_id=change_set_id
            )
        )
        return payload

    def move_change_sets_to_directory(
        self,
        *,
        dir_path: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Move several change sets into a directory.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["moveChangeSetsToDirectory"](
                network_id=self._network(network_id), dir_path=dir_path, body=body
            )
        )
        return payload

    def rename_change_set_directory(
        self,
        *,
        dir_path: str,
        name: str,
        network_id: str | None = None,
    ) -> Any:
        """Rename a directory.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["renameChangeSetDirectory"](
                network_id=self._network(network_id), dir_path=dir_path, name=name
            )
        )
        return payload
