# Generated from src/forward_sdk/_async/services/_generated/collectors.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Collectors.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["CollectorsService"]


class CollectorsService(Service):
    """Collectors."""

    def create_collector_account(
        self,
        *,
        body: Any,
    ) -> models.CollectorWithAuthKey:
        """Register a new collector account for the org.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["createCollectorAccount"](body=body))
        return models.CollectorWithAuthKey.model_validate(payload or {})

    def delete_collector_account(
        self,
        *,
        collector_name: str,
    ) -> Any:
        """Delete a collector account and all related state.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteCollectorAccount"](collector_name=collector_name)
        )
        return payload

    def upgrade_collector(
        self,
        *,
        collector_name: str,
    ) -> Any:
        """Upgrade one collector, if it is online and supports it.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["upgradeCollector"](collector_name=collector_name))
        return payload

    def upgrade_collectors(
        self,
    ) -> Any:
        """Upgrade every online collector in the org that supports it.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["upgradeCollectors"]())
        return payload
