# Generated from src/forward_sdk/_async/services/_generated/collector_binding.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Collector Binding.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["CollectorBindingService"]


class CollectorBindingService(Service):
    """Collector Binding."""

    def get_network_collector(
        self,
        *,
        network_id: str | None = None,
    ) -> models.CollectorWithStatus:
        """The collector bound to a network, with its connection and health.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getNetworkCollector"](network_id=self._network(network_id))
        )
        return models.CollectorWithStatus.model_validate(payload or {})

    def set_network_collector(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Bind a network to a collector, by the collector's username.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["setNetworkCollector"](network_id=self._network(network_id), body=body)
        )
        return payload

    def unbind_network_collector(
        self,
        *,
        network_id: str | None = None,
    ) -> Any:
        """Unbind the network from its collector.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["unbindNetworkCollector"](network_id=self._network(network_id))
        )
        return payload
