# Generated from src/forward_sdk/_async/services/_generated/collector_tasks.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Collector Tasks.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["CollectorTasksService"]


class CollectorTasksService(Service):
    """Collector Tasks."""

    def add_collector_task(
        self,
        *,
        network_id: str,
        type: str = "NETWORK_COLLECTION",
    ) -> models.StartCollectionResponse:
        """Add a collector task."""
        payload = self._send_json(
            ops.BUILDERS["addCollectorTask"](network_id=network_id, type=type)
        )
        return models.StartCollectionResponse.model_validate(payload or {})

    def get_collector_task(
        self,
        *,
        task_id: str,
    ) -> models.CollectorTask:
        """Get a collector task."""
        payload = self._send_json(ops.BUILDERS["getCollectorTask"](task_id=task_id))
        return models.CollectorTask.model_validate(payload or {})

    def get_collector_tasks(
        self,
        *,
        status: Sequence[str] | None = None,
        limit: int | None = None,
    ) -> Any:
        """Get collector tasks."""
        payload = self._send_json(ops.BUILDERS["getCollectorTasks"](status=status, limit=limit))
        return payload

    def stop_collector_task(
        self,
        *,
        task_id: str,
        note: str | None = None,
    ) -> Any:
        """Stop a collector task."""
        payload = self._send_json(ops.BUILDERS["stopCollectorTask"](task_id=task_id, note=note))
        return payload
