# Generated from src/forward_sdk/_async/services/_generated/collection_schedules.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Collection Schedules.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["CollectionSchedulesService"]


class CollectionSchedulesService(Service):
    """Collection Schedules."""

    def add_collection_schedule(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.CollectionSchedule:
        """Add a network collection schedule.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["addCollectionSchedule"](network_id=self._network(network_id), body=body)
        )
        return models.CollectionSchedule.model_validate(payload or {})

    def delete_collection_schedule(
        self,
        *,
        schedule_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a network collection schedule.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteCollectionSchedule"](
                network_id=self._network(network_id), schedule_id=schedule_id
            )
        )
        return payload

    def get_collection_schedule(
        self,
        *,
        schedule_id: str,
        network_id: str | None = None,
    ) -> models.CollectionSchedule:
        """Get a network collection schedule.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getCollectionSchedule"](
                network_id=self._network(network_id), schedule_id=schedule_id
            )
        )
        return models.CollectionSchedule.model_validate(payload or {})

    def get_collection_schedules(
        self,
        *,
        network_id: str | None = None,
    ) -> models.CollectionSchedules:
        """Get a network's collection schedules.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getCollectionSchedules"](network_id=self._network(network_id))
        )
        return models.CollectionSchedules.model_validate(payload or {})

    def replace_collection_schedule(
        self,
        *,
        schedule_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace a network collection schedule.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["replaceCollectionSchedule"](
                network_id=self._network(network_id), schedule_id=schedule_id, body=body
            )
        )
        return payload
