# Generated from src/forward_sdk/_async/services/_generated/configuration.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Configuration.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["ConfigurationService"]


class ConfigurationService(Service):
    """Configuration."""

    def clear_deployment_config_value(
        self,
        *,
        property: str,
    ) -> Any:
        """Remove a deployment property's override, reverting to its default.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["clearDeploymentConfigValue"](property=property))
        return payload

    def clear_org_config_value(
        self,
        *,
        property: str,
    ) -> Any:
        """Remove the calling user's org override, reverting to the default.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["clearOrgConfigValue"](property=property))
        return payload

    def clear_org_scoped_config_value(
        self,
        *,
        org_id: str,
        property: str,
    ) -> Any:
        """Remove a named org's override, reverting to the default.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["clearOrgScopedConfigValue"](org_id=org_id, property=property)
        )
        return payload

    def get_deployment_config(
        self,
    ) -> models.ConfigValues:
        """Every deployment property and its effective value.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["getDeploymentConfig"]())
        return models.ConfigValues.model_validate(payload or {})

    def get_deployment_config_value(
        self,
        *,
        property: str,
    ) -> models.ConfigValue:
        """A deployment property's effective value.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["getDeploymentConfigValue"](property=property))
        return models.ConfigValue.model_validate(payload or {})

    def get_global_config_value(
        self,
        *,
        property: str,
    ) -> models.ConfigValue:
        """An org property's global default.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["getGlobalConfigValue"](property=property))
        return models.ConfigValue.model_validate(payload or {})

    def get_org_config_value(
        self,
        *,
        property: str,
    ) -> models.ConfigValue:
        """An org property's effective value for the calling user's org.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["getOrgConfigValue"](property=property))
        return models.ConfigValue.model_validate(payload or {})

    def get_org_scoped_config_value(
        self,
        *,
        org_id: str,
        property: str,
    ) -> models.ConfigValue:
        """An org property's effective value for a named org.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getOrgScopedConfigValue"](org_id=org_id, property=property)
        )
        return models.ConfigValue.model_validate(payload or {})

    def set_deployment_config_value(
        self,
        *,
        property: str,
        value: str,
    ) -> models.ConfigValue:
        """Set a deployment property.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["setDeploymentConfigValue"](property=property, value=value)
        )
        return models.ConfigValue.model_validate(payload or {})

    def set_global_config_value(
        self,
        *,
        property: str,
        value: str,
    ) -> models.ConfigValue:
        """Change an org property's global default.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["setGlobalConfigValue"](property=property, value=value)
        )
        return models.ConfigValue.model_validate(payload or {})

    def set_org_config_value(
        self,
        *,
        property: str,
        value: str,
    ) -> models.ConfigValue:
        """Set an org property for the calling user's org.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["setOrgConfigValue"](property=property, value=value))
        return models.ConfigValue.model_validate(payload or {})

    def set_org_scoped_config_value(
        self,
        *,
        org_id: str,
        property: str,
        value: str,
    ) -> models.ConfigValue:
        """Set an org property for a named org.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["setOrgScopedConfigValue"](org_id=org_id, property=property, value=value)
        )
        return models.ConfigValue.model_validate(payload or {})
