# Generated from src/forward_sdk/_async/services/_generated/connectivity_tests.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Connectivity Tests.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["ConnectivityTestsService"]


class ConnectivityTestsService(Service):
    """Connectivity Tests."""

    def bulk_start_connectivity_tests(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Start a connectivity test for the given classic devices.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["bulkStartConnectivityTests"](
                network_id=self._network(network_id), body=body
            )
        )
        return payload

    def bulk_start_network_endpoint_connectivity_tests(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Start a connectivity test for the given network endpoints.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["bulkStartNetworkEndpointConnectivityTests"](
                network_id=self._network(network_id), body=body
            )
        )
        return payload

    def bulk_stop_connectivity_tests(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Stop the connectivity tests running for the given sources.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["bulkStopConnectivityTests"](
                network_id=self._network(network_id), body=body
            )
        )
        return payload

    def get_connectivity_test_phase_results(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> list[models.DeviceTestPhaseResult]:
        """The same result, broken out by phase.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getConnectivityTestPhaseResults"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return [models.DeviceTestPhaseResult.model_validate(row) for row in payload or []]

    def get_connectivity_test_result(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> models.SourceConnectivityResult:
        """One source's most recent connectivity test result.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getConnectivityTestResult"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return models.SourceConnectivityResult.model_validate(payload or {})

    def get_connectivity_test_results(
        self,
        *,
        network_id: str | None = None,
    ) -> list[models.ConnectivityTestResult]:
        """Every source's most recent connectivity test result.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getConnectivityTestResults"](network_id=self._network(network_id))
        )
        return [models.ConnectivityTestResult.model_validate(row) for row in payload or []]

    def start_connectivity_test(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Start a connectivity test for one classic device.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["startConnectivityTest"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return payload

    def start_connectivity_tests(
        self,
        *,
        network_id: str | None = None,
    ) -> Any:
        """Start a connectivity test for every classic device in the network.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["startConnectivityTests"](network_id=self._network(network_id))
        )
        return payload

    def start_network_endpoint_connectivity_test(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Start a connectivity test for one network endpoint.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["startNetworkEndpointConnectivityTest"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return payload

    def stop_connectivity_test(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Stop the connectivity test running for one source.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["stopConnectivityTest"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return payload

    def stop_connectivity_tests(
        self,
        *,
        network_id: str | None = None,
    ) -> Any:
        """Stop every running connectivity test in the network.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["stopConnectivityTests"](network_id=self._network(network_id))
        )
        return payload
