# Generated from src/forward_sdk/_async/services/_generated/credentials.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Credentials.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["CredentialsService"]


class CredentialsService(Service):
    """Credentials.

    May be unavailable on your instance (admin); see docs/gating.md.
    """

    def create_cli_credential(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.CliCredential:
        """Create a CLI credential.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["createCliCredential"](network_id=self._network(network_id), body=body)
        )
        return models.CliCredential.model_validate(payload or {})

    def create_cli_credentials(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> list[models.StoredCliCredential]:
        """Create CLI credentials.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["createCliCredentials"](network_id=self._network(network_id), body=body)
        )
        return [models.StoredCliCredential.model_validate(row) for row in payload or []]

    def create_http_credential(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.HttpCredential:
        """Create an HTTP credential.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["createHttpCredential"](network_id=self._network(network_id), body=body)
        )
        return models.HttpCredential.model_validate(payload or {})

    def create_http_credentials(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> list[models.StoredHttpCredential]:
        """Create HTTP credentials.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["createHttpCredentials"](network_id=self._network(network_id), body=body)
        )
        return [models.StoredHttpCredential.model_validate(row) for row in payload or []]

    def delete_cli_credential(
        self,
        *,
        credential_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a CLI credential.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteCliCredential"](
                network_id=self._network(network_id), credential_id=credential_id
            )
        )
        return payload

    def delete_http_credential(
        self,
        *,
        credential_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete an HTTP credential.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteHttpCredential"](
                network_id=self._network(network_id), credential_id=credential_id
            )
        )
        return payload

    def get_cli_credential(
        self,
        *,
        credential_id: str,
        network_id: str | None = None,
    ) -> models.StoredCliCredential:
        """Get a CLI credential.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["getCliCredential"](
                network_id=self._network(network_id), credential_id=credential_id
            )
        )
        return models.StoredCliCredential.model_validate(payload or {})

    def get_cli_credentials(
        self,
        *,
        network_id: str | None = None,
    ) -> list[models.StoredCliCredential]:
        """Get all CLI credentials.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["getCliCredentials"](network_id=self._network(network_id))
        )
        return [models.StoredCliCredential.model_validate(row) for row in payload or []]

    def get_http_credential(
        self,
        *,
        credential_id: str,
        network_id: str | None = None,
    ) -> models.StoredHttpCredential:
        """Get an HTTP credential.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["getHttpCredential"](
                network_id=self._network(network_id), credential_id=credential_id
            )
        )
        return models.StoredHttpCredential.model_validate(payload or {})

    def get_http_credentials(
        self,
        *,
        network_id: str | None = None,
    ) -> list[models.StoredHttpCredential]:
        """Get all HTTP credentials.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["getHttpCredentials"](network_id=self._network(network_id))
        )
        return [models.StoredHttpCredential.model_validate(row) for row in payload or []]

    def patch_cli_credential(
        self,
        *,
        credential_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.StoredCliCredential:
        """Update a CLI credential.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["patchCliCredential"](
                network_id=self._network(network_id), credential_id=credential_id, body=body
            )
        )
        return models.StoredCliCredential.model_validate(payload or {})

    def patch_http_credential(
        self,
        *,
        credential_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Update an HTTP credential.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["patchHttpCredential"](
                network_id=self._network(network_id), credential_id=credential_id, body=body
            )
        )
        return payload
