# Generated from src/forward_sdk/_async/services/_generated/dashboards.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Dashboards.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["DashboardsService"]


class DashboardsService(Service):
    """Dashboards."""

    def create_dashboard(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Create an empty dashboard.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["createDashboard"](network_id=self._network(network_id), body=body)
        )
        return payload

    def delete_dashboard(
        self,
        *,
        dashboard_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a dashboard and its display settings.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteDashboard"](
                network_id=self._network(network_id), dashboard_id=dashboard_id
            )
        )
        return payload

    def get_dashboard(
        self,
        *,
        dashboard_id: str,
        network_id: str | None = None,
    ) -> models.Dashboard:
        """One dashboard with its layout.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getDashboard"](
                network_id=self._network(network_id), dashboard_id=dashboard_id
            )
        )
        return models.Dashboard.model_validate(payload or {})

    def get_dashboard_display_settings(
        self,
        *,
        dashboard_id: str,
        network_id: str | None = None,
    ) -> models.DashboardDisplaySettings:
        """A dashboard's full-screen auto-scroll settings.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getDashboardDisplaySettings"](
                network_id=self._network(network_id), dashboard_id=dashboard_id
            )
        )
        return models.DashboardDisplaySettings.model_validate(payload or {})

    def list_dashboards(
        self,
        *,
        network_id: str | None = None,
    ) -> list[models.Dashboard]:
        """A network's composed dashboards.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["listDashboards"](network_id=self._network(network_id))
        )
        return [models.Dashboard.model_validate(row) for row in payload or []]

    def list_default_dashboards(
        self,
        *,
        network_id: str | None = None,
    ) -> list[models.Dashboard]:
        """The dashboards Forward ships, which cannot be changed.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["listDefaultDashboards"](network_id=self._network(network_id))
        )
        return [models.Dashboard.model_validate(row) for row in payload or []]

    def remove_panels_from_dashboards(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Remove every embedding of the given panels from every dashboard in the network.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["removePanelsFromDashboards"](
                network_id=self._network(network_id), body=body
            )
        )
        return payload

    def update_dashboard(
        self,
        *,
        dashboard_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Rename a dashboard, change its description, or replace its layout.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["updateDashboard"](
                network_id=self._network(network_id), dashboard_id=dashboard_id, body=body
            )
        )
        return payload

    def update_dashboard_display_settings(
        self,
        *,
        dashboard_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Change a dashboard's full-screen auto-scroll settings.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["updateDashboardDisplaySettings"](
                network_id=self._network(network_id), dashboard_id=dashboard_id, body=body
            )
        )
        return payload
