# Generated from src/forward_sdk/_async/services/_generated/data_connectors.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Data Connectors.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["DataConnectorsService"]


class DataConnectorsService(Service):
    """Data Connectors.

    May be unavailable on your instance (admin); see docs/gating.md.
    """

    def add_data_connector(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.DataConnector:
        """Add a data connector.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["addDataConnector"](network_id=self._network(network_id), body=body)
        )
        return models.DataConnector.model_validate(payload or {})

    def delete_data_connector(
        self,
        *,
        name: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a data connector.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteDataConnector"](network_id=self._network(network_id), name=name)
        )
        return payload

    def get_data_connector(
        self,
        *,
        name: str,
        network_id: str | None = None,
        with_: Sequence[str] | None = None,
    ) -> models.DataConnector:
        """Get a data connector.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["getDataConnector"](
                network_id=self._network(network_id), name=name, with_=with_
            )
        )
        return models.DataConnector.model_validate(payload or {})

    def get_data_connectors(
        self,
        *,
        network_id: str | None = None,
        with_: Sequence[str] | None = None,
    ) -> models.DataConnectors:
        """Get a network's data connectors.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["getDataConnectors"](network_id=self._network(network_id), with_=with_)
        )
        return models.DataConnectors.model_validate(payload or {})

    def test_data_connector(
        self,
        *,
        name: str,
        network_id: str | None = None,
    ) -> models.DataConnectorTestResult:
        """Test a data connector.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["testDataConnector"](network_id=self._network(network_id), name=name)
        )
        return models.DataConnectorTestResult.model_validate(payload or {})

    def update_data_connector(
        self,
        *,
        name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.DataConnector:
        """Update a data connector.

        Uses the client's network when ``network_id`` is omitted.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(
            ops.BUILDERS["updateDataConnector"](
                network_id=self._network(network_id), name=name, body=body
            )
        )
        return models.DataConnector.model_validate(payload or {})
