# Generated from src/forward_sdk/_async/services/_generated/encryptors.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Encryptors.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["EncryptorsService"]


class EncryptorsService(Service):
    """Encryptors."""

    def delete_encryptor(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Remove an encryptor.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteEncryptor"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return payload

    def get_encryptor(
        self,
        *,
        device_name: str,
        network_id: str | None = None,
    ) -> models.Encryptor:
        """Get an encryptor.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getEncryptor"](
                network_id=self._network(network_id), device_name=device_name
            )
        )
        return models.Encryptor.model_validate(payload or {})

    def get_encryptors(
        self,
        *,
        network_id: str | None = None,
    ) -> models.EncryptorList:
        """Get a network's encryptors.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getEncryptors"](network_id=self._network(network_id))
        )
        return models.EncryptorList.model_validate(payload or {})

    def patch_encryptor(
        self,
        *,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.Encryptor:
        """Update an encryptor.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["patchEncryptor"](
                network_id=self._network(network_id), device_name=device_name, body=body
            )
        )
        return models.Encryptor.model_validate(payload or {})

    def put_encryptor(
        self,
        *,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add or replace an encryptor.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["putEncryptor"](
                network_id=self._network(network_id), device_name=device_name, body=body
            )
        )
        return payload

    def put_encryptors(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace all of a network's encryptors.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["putEncryptors"](network_id=self._network(network_id), body=body)
        )
        return payload
