# Generated from src/forward_sdk/_async/services/_generated/firewall_predict.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Firewall Predict.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["FirewallPredictService"]


class FirewallPredictService(Service):
    """Firewall Predict."""

    def add_security_rule(
        self,
        *,
        change_set_id: str,
        device_name: str,
        scope_id: str,
        rulebase_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add a security rule to a firewall's rulebase.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["addSecurityRule"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                scope_id=scope_id,
                rulebase_id=rulebase_id,
                body=body,
            )
        )
        return payload

    def delete_security_rule(
        self,
        *,
        change_set_id: str,
        device_name: str,
        scope_id: str,
        rulebase_id: str,
        rule_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a security rule.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteSecurityRule"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                scope_id=scope_id,
                rulebase_id=rulebase_id,
                rule_id=rule_id,
            )
        )
        return payload

    def discard_security_rule_changes(
        self,
        *,
        change_set_id: str,
        device_name: str,
        scope_id: str,
        rulebase_id: str,
        rule_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Discard the change set's pending change to one rule.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["discardSecurityRuleChanges"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                scope_id=scope_id,
                rulebase_id=rulebase_id,
                rule_id=rule_id,
            )
        )
        return payload

    def get_security_rules_diff(
        self,
        *,
        change_set_id: str,
        device_name: str,
        network_id: str | None = None,
    ) -> models.SecurityRulesDiff:
        """A firewall's rulebases and how the change set alters its rules.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getSecurityRulesDiff"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
            )
        )
        return models.SecurityRulesDiff.model_validate(payload or {})

    def update_security_rule(
        self,
        *,
        change_set_id: str,
        device_name: str,
        scope_id: str,
        rulebase_id: str,
        rule_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace a rule's definition, or move it.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["updateSecurityRule"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                scope_id=scope_id,
                rulebase_id=rulebase_id,
                rule_id=rule_id,
                body=body,
            )
        )
        return payload
