# Generated from src/forward_sdk/_async/services/_generated/internet_exposure.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Internet Exposure.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["InternetExposureService"]


class InternetExposureService(Service):
    """Internet Exposure."""

    def get_internet_exposed_host_connectivity(
        self,
        *,
        snapshot_id: str,
        exposed_host_id: str,
    ) -> models.ConnectivityDetails:
        """Sample connectivity from the internet node to one exposed host.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getInternetExposedHostConnectivity"](
                snapshot_id=snapshot_id, exposed_host_id=exposed_host_id
            )
        )
        return models.ConnectivityDetails.model_validate(payload or {})

    def get_internet_exposed_hosts(
        self,
        *,
        snapshot_id: str,
    ) -> models.HostsExposureResponse:
        """Hosts exposed through the internet node, with scanner vulnerability counts.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["getInternetExposedHosts"](snapshot_id=snapshot_id))
        return models.HostsExposureResponse.model_validate(payload or {})

    def get_internet_exposure(
        self,
        *,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.InternetExposure:
        """Interfaces that receive traffic from the internet node.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getInternetExposure"](
                network_id=self._network(network_id), snapshot_id=self._snapshot(snapshot_id)
            )
        )
        return models.InternetExposure.model_validate(payload or {})
