# Generated from src/forward_sdk/_async/services/_generated/internet_node.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Internet Node.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["InternetNodeService"]


class InternetNodeService(Service):
    """Internet Node."""

    def add_internet_node_connection(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add a connection to the internet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["addInternetNodeConnection"](
                network_id=self._network(network_id), body=body
            )
        )
        return payload

    def delete_internet_node_connections(
        self,
        *,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Remove internet node connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteInternetNodeConnections"](
                network_id=self._network(network_id),
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    def get_internet_node(
        self,
        *,
        network_id: str | None = None,
    ) -> models.InternetNode:
        """Get the network's internet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getInternetNode"](network_id=self._network(network_id))
        )
        return models.InternetNode.model_validate(payload or {})

    def get_internet_node_connections(
        self,
        *,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Get the internet node's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getInternetNodeConnections"](
                network_id=self._network(network_id),
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    def put_internet_node(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace the network's internet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["putInternetNode"](network_id=self._network(network_id), body=body)
        )
        return payload

    def update_internet_node(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.InternetNode:
        """Update the network's internet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["updateInternetNode"](network_id=self._network(network_id), body=body)
        )
        return models.InternetNode.model_validate(payload or {})
