# Generated from src/forward_sdk/_async/services/_generated/intranet_nodes.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Intranet Nodes.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["IntranetNodesService"]


class IntranetNodesService(Service):
    """Intranet Nodes."""

    def add_intranet_node_connection(
        self,
        *,
        node_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add a connection to an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["addIntranetNodeConnection"](
                network_id=self._network(network_id), node_name=node_name, body=body
            )
        )
        return payload

    def backdate_intranet_nodes(
        self,
        *,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> Any:
        """Apply recent intranet node changes to an existing snapshot.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["backdateIntranetNodes"](
                network_id=self._network(network_id), snapshot_id=self._snapshot(snapshot_id)
            )
        )
        return payload

    def compute_intranet_node_connections(
        self,
        *,
        query_id: str,
        network_id: str | None = None,
    ) -> models.L3DynamicConnectionsComputeResult:
        """Preview the connections an NQE query would produce.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["computeIntranetNodeConnections"](
                network_id=self._network(network_id), query_id=query_id
            )
        )
        return models.L3DynamicConnectionsComputeResult.model_validate(payload or {})

    def delete_intranet_node(
        self,
        *,
        node_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Remove an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteIntranetNode"](
                network_id=self._network(network_id), node_name=node_name
            )
        )
        return payload

    def delete_intranet_node_connections(
        self,
        *,
        node_name: str,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Remove an intranet node's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteIntranetNodeConnections"](
                network_id=self._network(network_id),
                node_name=node_name,
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    def get_intranet_node(
        self,
        *,
        node_name: str,
        network_id: str | None = None,
    ) -> models.IntranetNode:
        """Get an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getIntranetNode"](
                network_id=self._network(network_id), node_name=node_name
            )
        )
        return models.IntranetNode.model_validate(payload or {})

    def get_intranet_node_connections(
        self,
        *,
        node_name: str,
        network_id: str | None = None,
        uplink_device: str | None = None,
        uplink_port: str | None = None,
        gateway_device: str | None = None,
        gateway_port: str | None = None,
        vlan: str | None = None,
    ) -> models.L3SyntheticWanConnections:
        """Get an intranet node's connections.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getIntranetNodeConnections"](
                network_id=self._network(network_id),
                node_name=node_name,
                uplink_device=uplink_device,
                uplink_port=uplink_port,
                gateway_device=gateway_device,
                gateway_port=gateway_port,
                vlan=vlan,
            )
        )
        return models.L3SyntheticWanConnections.model_validate(payload or {})

    def get_intranet_nodes(
        self,
        *,
        network_id: str | None = None,
    ) -> models.IntranetNodeList:
        """Get a network's intranet nodes.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getIntranetNodes"](network_id=self._network(network_id))
        )
        return models.IntranetNodeList.model_validate(payload or {})

    def patch_intranet_node(
        self,
        *,
        node_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.IntranetNode:
        """Update an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["patchIntranetNode"](
                network_id=self._network(network_id), node_name=node_name, body=body
            )
        )
        return models.IntranetNode.model_validate(payload or {})

    def put_intranet_node(
        self,
        *,
        node_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add or replace an intranet node.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["putIntranetNode"](
                network_id=self._network(network_id), node_name=node_name, body=body
            )
        )
        return payload

    def put_intranet_nodes(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace all of a network's intranet nodes.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["putIntranetNodes"](network_id=self._network(network_id), body=body)
        )
        return payload
