# Generated from src/forward_sdk/_async/services/_generated/legacy_collection.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Legacy Collection.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

import warnings
from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["LegacyCollectionService"]


class LegacyCollectionService(Service):
    """Legacy Collection."""

    def cancel_collect(
        self,
        *,
        network_id: str | None = None,
    ) -> Any:
        """Cancel an in-progress network collection.

        Deprecated by Forward.
        Uses the client's network when ``network_id`` is omitted.
        """
        warnings.warn(
            "cancelCollect is deprecated in the Forward API",
            DeprecationWarning,
            stacklevel=2,
        )
        payload = self._send_json(
            ops.BUILDERS["cancelCollect"](network_id=self._network(network_id))
        )
        return payload

    def collect(
        self,
        *,
        network_id: str | None = None,
    ) -> Any:
        """Trigger a network collection.

        Deprecated by Forward.
        Uses the client's network when ``network_id`` is omitted.
        """
        warnings.warn(
            "collect is deprecated in the Forward API",
            DeprecationWarning,
            stacklevel=2,
        )
        payload = self._send_json(ops.BUILDERS["collect"](network_id=self._network(network_id)))
        return payload

    def get_collector_state(
        self,
        *,
        network_id: str | None = None,
    ) -> models.CollectorState:
        """Get the status of a network's collector.

        Deprecated by Forward.
        Uses the client's network when ``network_id`` is omitted.
        """
        warnings.warn(
            "getCollectorState is deprecated in the Forward API",
            DeprecationWarning,
            stacklevel=2,
        )
        payload = self._send_json(
            ops.BUILDERS["getCollectorState"](network_id=self._network(network_id))
        )
        return models.CollectorState.model_validate(payload or {})
