# Generated from src/forward_sdk/_async/services/_generated/nqe_panels.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""NQE Panels.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["NQEPanelsService"]


class NQEPanelsService(Service):
    """NQE Panels."""

    def create_nqe_panel(
        self,
        *,
        body: Any,
    ) -> models.NqePanel:
        """Create an NQE panel.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["createNqePanel"](body=body))
        return models.NqePanel.model_validate(payload or {})

    def delete_nqe_panel(
        self,
        *,
        panel_id: str,
    ) -> Any:
        """Delete a panel.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["deleteNqePanel"](panel_id=panel_id))
        return payload

    def delete_nqe_panels(
        self,
        *,
        body: Any,
    ) -> Any:
        """Delete several panels.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["deleteNqePanels"](body=body))
        return payload

    def get_nqe_panel_metrics(
        self,
        *,
        body: Any,
        result_key: str,
        network_id: str | None = None,
    ) -> models.NqePanelMetrics:
        """Metric panels' values over one query execution's result.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getNqePanelMetrics"](
                network_id=self._network(network_id), body=body, result_key=result_key
            )
        )
        return models.NqePanelMetrics.model_validate(payload or {})

    def list_nqe_panels(
        self,
    ) -> models.NqePanels:
        """The org's NQE panels, each with where it is used.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["listNqePanels"]())
        return models.NqePanels.model_validate(payload or {})

    def preview_nqe_metric(
        self,
        *,
        body: Any,
        result_key: str,
        network_id: str | None = None,
    ) -> models.NqeMetricPreviewResult:
        """Compute a metric over a result without saving a panel.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["previewNqeMetric"](
                network_id=self._network(network_id), body=body, result_key=result_key
            )
        )
        return models.NqeMetricPreviewResult.model_validate(payload or {})

    def update_nqe_panel(
        self,
        *,
        panel_id: str,
        body: Any,
    ) -> models.NqePanel:
        """Change a panel's name, presentation or configuration.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(ops.BUILDERS["updateNqePanel"](panel_id=panel_id, body=body))
        return models.NqePanel.model_validate(payload or {})
