# Generated from src/forward_sdk/_async/services/_generated/predict_assist.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Predict Assist.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["PredictAssistService"]


class PredictAssistService(Service):
    """Predict Assist."""

    def assist_change_set_commands(
        self,
        *,
        change_set_id: str,
        device_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.CliAssistResponse:
        """Ask Forward AI to draft CLI commands for a device from a prompt.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["assistChangeSetCommands"](
                network_id=self._network(network_id),
                change_set_id=change_set_id,
                device_name=device_name,
                body=body,
            )
        )
        return models.CliAssistResponse.model_validate(payload or {})

    def assist_change_set_overview(
        self,
        *,
        change_set_id: str,
        network_id: str | None = None,
    ) -> models.OverviewAssistResponse:
        """Ask Forward AI to name and describe the change set from its contents.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["assistChangeSetOverview"](
                network_id=self._network(network_id), change_set_id=change_set_id
            )
        )
        return models.OverviewAssistResponse.model_validate(payload or {})

    def assist_config_diff_summary(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.SummaryAssistResponse:
        """Ask Forward AI to summarize the configuration changes between two snapshots.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["assistConfigDiffSummary"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.SummaryAssistResponse.model_validate(payload or {})

    def assist_impact_diff_summary(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.SummaryAssistResponse:
        """Ask Forward AI to summarize the impact of the changes between two snapshots.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["assistImpactDiffSummary"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.SummaryAssistResponse.model_validate(payload or {})
