# Generated from src/forward_sdk/_async/services/_generated/resource_pools.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Resource Pools.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["ResourcePoolsService"]


class ResourcePoolsService(Service):
    """Resource Pools."""

    def analyze_resource_pool(
        self,
        *,
        body: Any,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.AnalyzedResourcePool:
        """Valid device/VRF/subnet combinations for a resource pool's filters.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["analyzeResourcePool"](
                network_id=self._network(network_id),
                body=body,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return models.AnalyzedResourcePool.model_validate(payload or {})

    def get_resource_pool_connectivity_details(
        self,
        *,
        body: Any,
        network_id: str | None = None,
        snapshot_id: str | None = None,
    ) -> models.ConnectivityDetails:
        """Sample connectivity between two resource pools.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        Uses the network's latest processed snapshot when ``snapshot_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getResourcePoolConnectivityDetails"](
                network_id=self._network(network_id),
                body=body,
                snapshot_id=self._snapshot(snapshot_id),
            )
        )
        return models.ConnectivityDetails.model_validate(payload or {})
