# Generated from src/forward_sdk/_async/services/_generated/security_matrix_filters.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Security Matrix Filters.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["SecurityMatrixFiltersService"]


class SecurityMatrixFiltersService(Service):
    """Security Matrix Filters."""

    def add_security_matrix_filter(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.SecurityMatrixFilter:
        """Save a security matrix filter.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["addSecurityMatrixFilter"](network_id=self._network(network_id), body=body)
        )
        return models.SecurityMatrixFilter.model_validate(payload or {})

    def delete_security_matrix_filter(
        self,
        *,
        filter_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete a saved security matrix filter.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteSecurityMatrixFilter"](
                network_id=self._network(network_id), filter_id=filter_id
            )
        )
        return payload

    def get_security_matrix_filters(
        self,
        *,
        network_id: str | None = None,
    ) -> models.SecurityMatrixFiltersList:
        """The network's saved security matrix filters.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getSecurityMatrixFilters"](network_id=self._network(network_id))
        )
        return models.SecurityMatrixFiltersList.model_validate(payload or {})

    def update_security_matrix_filter(
        self,
        *,
        filter_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.SecurityMatrixFilter:
        """Change a saved security matrix filter.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["updateSecurityMatrixFilter"](
                network_id=self._network(network_id), filter_id=filter_id, body=body
            )
        )
        return models.SecurityMatrixFilter.model_validate(payload or {})
