# Generated from src/forward_sdk/_async/services/_generated/snapshot_diff_details.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""Snapshot Diff Details.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["SnapshotDiffDetailsService"]


class SnapshotDiffDetailsService(Service):
    """Snapshot Diff Details."""

    def compute_nqe_check_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        body: Any,
    ) -> Any:
        """Start computing diffs for the given NQE checks.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["computeNqeCheckDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                body=body,
            )
        )
        return payload

    def get_acl_diff_stats(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.DeviceDiffStats:
        """Per-device ACL change statistics.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getAclDiffStats"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.DeviceDiffStats.model_validate(payload or {})

    def get_arp_diff_stats(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.DeviceDiffStats:
        """Per-device ARP change statistics.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getArpDiffStats"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.DeviceDiffStats.model_validate(payload or {})

    def get_check_diff_counts(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.CheckDiffCounts:
        """How many checks changed, by check type.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getCheckDiffCounts"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.CheckDiffCounts.model_validate(payload or {})

    def get_check_diff_details(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        check_id: str,
    ) -> models.CheckDiffDetails:
        """How one predefined check's findings changed.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getCheckDiffDetails"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                check_id=check_id,
            )
        )
        return models.CheckDiffDetails.model_validate(payload or {})

    def get_check_diff_stats(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        type: str = "Predefined",
    ) -> models.CheckDiffStats:
        """Added, deleted, modified and unchanged findings per check.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getCheckDiffStats"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                type=type,
            )
        )
        return models.CheckDiffStats.model_validate(payload or {})

    def get_check_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        type: Sequence[str],
    ) -> models.ChecksDiff:
        """Check results that changed, for the given check types.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getCheckDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                type=type,
            )
        )
        return models.ChecksDiff.model_validate(payload or {})

    def get_cloud_acl_diff_count(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.DiffCount:
        """How many cloud objects have ACL changes.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getCloudAclDiffCount"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.DiffCount.model_validate(payload or {})

    def get_cloud_acl_diff_stats(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.CloudObjectDiffStats:
        """Per-cloud-object ACL change statistics.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getCloudAclDiffStats"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.CloudObjectDiffStats.model_validate(payload or {})

    def get_cloud_object_acl_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        object_id: str,
    ) -> Any:
        """One cloud object's ACL changes.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getCloudObjectAclDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                object_id=object_id,
            )
        )
        return payload

    def get_cloud_object_diff_count(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.DiffCount:
        """How many cloud objects changed.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getCloudObjectDiffCount"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.DiffCount.model_validate(payload or {})

    def get_cloud_object_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> list[models.CloudObjectDiffEntry]:
        """Cloud objects added, removed or modified.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getCloudObjectDiffs"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return [models.CloudObjectDiffEntry.model_validate(row) for row in payload or []]

    def get_connectivity_diff_location_pair(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        loc1: str,
        loc2: str,
    ) -> models.LocationPairConnDiffStats:
        """Subnet pairs that changed between two locations.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getConnectivityDiffLocationPair"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                loc1=loc1,
                loc2=loc2,
            )
        )
        return models.LocationPairConnDiffStats.model_validate(payload or {})

    def get_connectivity_diff_location_pairs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        type: str,
        loc: str | None = None,
    ) -> models.LocationConnChangeCounts:
        """Changed subnet pairs counted per location pair.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getConnectivityDiffLocationPairs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                type=type,
                loc=loc,
            )
        )
        return models.LocationConnChangeCounts.model_validate(payload or {})

    def get_connectivity_diff_locations(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.LocationsConnDiffStats:
        """Incoming and outgoing connectivity changes per location.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getConnectivityDiffLocations"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.LocationsConnDiffStats.model_validate(payload or {})

    def get_connectivity_diff_subnet_pair(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        loc1: str,
        loc2: str,
        src: str,
        dst: str,
    ) -> models.SubnetConnDiffDetails:
        """How connectivity changed between two subnets.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getConnectivityDiffSubnetPair"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                loc1=loc1,
                loc2=loc2,
                src=src,
                dst=dst,
            )
        )
        return models.SubnetConnDiffDetails.model_validate(payload or {})

    def get_device_acl_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        device_name: str,
    ) -> models.DeviceAclDiff:
        """One device's ACL entry changes.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getDeviceAclDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                device_name=device_name,
            )
        )
        return models.DeviceAclDiff.model_validate(payload or {})

    def get_device_arp_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        device_name: str,
    ) -> models.DeviceArpDiff:
        """One device's ARP table changes.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getDeviceArpDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                device_name=device_name,
            )
        )
        return models.DeviceArpDiff.model_validate(payload or {})

    def get_device_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> list[models.DeviceDiffEntry]:
        """Devices added or removed.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getDeviceDiffs"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return [models.DeviceDiffEntry.model_validate(row) for row in payload or []]

    def get_device_interface_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        device_name: str,
    ) -> models.DeviceInterfaceDiff:
        """One device's interface changes.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getDeviceInterfaceDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                device_name=device_name,
            )
        )
        return models.DeviceInterfaceDiff.model_validate(payload or {})

    def get_device_mac_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        device_name: str,
    ) -> models.DeviceMacDiff:
        """One device's MAC table changes.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getDeviceMacDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                device_name=device_name,
            )
        )
        return models.DeviceMacDiff.model_validate(payload or {})

    def get_device_nat_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        device_name: str,
    ) -> models.DeviceNatDiff:
        """One device's NAT entry changes.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getDeviceNatDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                device_name=device_name,
            )
        )
        return models.DeviceNatDiff.model_validate(payload or {})

    def get_device_routing_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        device_name: str,
    ) -> models.RoutingDiffDetails:
        """One device's routing table changes.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getDeviceRoutingDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                device_name=device_name,
            )
        )
        return models.RoutingDiffDetails.model_validate(payload or {})

    def get_file_diff_count(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.FileDiffCount:
        """How many devices have changed files, by file type.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getFileDiffCount"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.FileDiffCount.model_validate(payload or {})

    def get_file_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        type: str | None = None,
    ) -> models.CollectedFilesDiff:
        """Which collected files changed, per device.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getFileDiffs"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                type=type,
            )
        )
        return models.CollectedFilesDiff.model_validate(payload or {})

    def get_interface_diff_stats(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.DeviceDiffStats:
        """Per-device interface change statistics.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getInterfaceDiffStats"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.DeviceDiffStats.model_validate(payload or {})

    def get_l2_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.L2Diff:
        """VLAN membership changes, per VLAN.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getL2Diffs"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.L2Diff.model_validate(payload or {})

    def get_mac_diff_stats(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.DeviceDiffStats:
        """Per-device MAC table change statistics.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getMacDiffStats"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.DeviceDiffStats.model_validate(payload or {})

    def get_nat_diff_stats(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.DeviceDiffStats:
        """Per-device NAT change statistics.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getNatDiffStats"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.DeviceDiffStats.model_validate(payload or {})

    def get_nqe_check_diff_stats(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.NqeCheckDiffStats:
        """Per-check statistics for NQE checks, with processing state.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getNqeCheckDiffStats"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.NqeCheckDiffStats.model_validate(payload or {})

    def get_nqe_check_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.ChecksDiff:
        """NQE check results that changed, without blocking.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getNqeCheckDiffs"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.ChecksDiff.model_validate(payload or {})

    def get_routing_diff_for_prefix(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        prefix: str,
    ) -> Any:
        """Routing changes for one prefix.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getRoutingDiffForPrefix"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                prefix=prefix,
            )
        )
        return payload

    def get_routing_diff_prefixes(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
        offset: int | None = None,
        limit: int | None = None,
        prefix_filter: str | None = None,
    ) -> Any:
        """Routing changes by prefix, paged.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getRoutingDiffPrefixes"](
                before_snapshot_id=before_snapshot_id,
                after_snapshot_id=after_snapshot_id,
                offset=offset,
                limit=limit,
                prefix_filter=prefix_filter,
            )
        )
        return payload

    def get_routing_diff_stats(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.DeviceDiffStats:
        """Per-device routing change statistics.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getRoutingDiffStats"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.DeviceDiffStats.model_validate(payload or {})

    def get_routing_diff_summary(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> Any:
        """A summary of routing changes.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getRoutingDiffSummary"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return payload

    def get_topology_diffs(
        self,
        *,
        before_snapshot_id: str,
        after_snapshot_id: str,
    ) -> models.TopologyDiff:
        """Links added and deleted.

        Unpublished: not part of Forward's documented API.
        """
        payload = self._send_json(
            ops.BUILDERS["getTopologyDiffs"](
                before_snapshot_id=before_snapshot_id, after_snapshot_id=after_snapshot_id
            )
        )
        return models.TopologyDiff.model_validate(payload or {})
