# Generated from src/forward_sdk/_async/services/_generated/snmp_credentials.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""SNMP Credentials.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["SNMPCredentialsService"]


class SNMPCredentialsService(Service):
    """SNMP Credentials."""

    def create_snmp_credential(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> models.SnmpCredential:
        """Create an SNMP credential.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["createSnmpCredential"](network_id=self._network(network_id), body=body)
        )
        return models.SnmpCredential.model_validate(payload or {})

    def delete_snmp_credential(
        self,
        *,
        credential_id: str,
        network_id: str | None = None,
    ) -> Any:
        """Delete an SNMP credential.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteSnmpCredential"](
                network_id=self._network(network_id), credential_id=credential_id
            )
        )
        return payload

    def list_snmp_credentials(
        self,
        *,
        network_id: str | None = None,
    ) -> list[models.SnmpCredential]:
        """A network's SNMP credentials.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["listSnmpCredentials"](network_id=self._network(network_id))
        )
        return [models.SnmpCredential.model_validate(row) for row in payload or []]

    def update_snmp_credential(
        self,
        *,
        credential_id: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Change an SNMP credential.

        Unpublished: not part of Forward's documented API.
        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["updateSnmpCredential"](
                network_id=self._network(network_id), credential_id=credential_id, body=body
            )
        )
        return payload
