# Generated from src/forward_sdk/_async/services/_generated/system_administration.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""System Administration.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["SystemAdministrationService"]


class SystemAdministrationService(Service):
    """System Administration.

    May be unavailable on your instance (admin, deployment, license); see docs/gating.md.
    """

    def get_cve_index(
        self,
    ) -> Iterator[bytes]:
        """Export the CVE index.

        May be unavailable (license, deployment, admin); see docs/gating.md.
        """
        with self._transport.stream(ops.BUILDERS["getCveIndex"]()) as response:
            for chunk in response.iter_bytes():
                yield chunk

    def put_cve_index(
        self,
        *,
        body: Any,
        sha: str | None = None,
    ) -> Any:
        """Import a new CVE index.

        May be unavailable (license, deployment, admin); see docs/gating.md.
        """
        payload = self._send_json(ops.BUILDERS["putCveIndex"](body=body, sha=sha))
        return payload
