# Generated from src/forward_sdk/_async/services/_generated/user_accounts.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""User Accounts.

Generated by scripts/gen_services.py -- do not edit.

These endpoints are not part of Forward's published API.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["UserAccountsService"]


class UserAccountsService(Service):
    """User Accounts.

    May be unavailable on your instance (admin); see docs/gating.md.
    """

    def create_user(
        self,
        *,
        body: Any,
    ) -> models.User:
        """Create a user account.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(ops.BUILDERS["createUser"](body=body))
        return models.User.model_validate(payload or {})

    def delete_user(
        self,
        *,
        user_id: str,
    ) -> Any:
        """Delete a user account.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(ops.BUILDERS["deleteUser"](user_id=user_id))
        return payload

    def get_current_user(
        self,
    ) -> models.CurrentUser:
        """Get the authenticated user.

        Unpublished: not part of Forward's documented API.
        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(ops.BUILDERS["getCurrentUser"]())
        return models.CurrentUser.model_validate(payload or {})

    def get_user(
        self,
        *,
        user_id: str,
    ) -> models.User:
        """Get a user account.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(ops.BUILDERS["getUser"](user_id=user_id))
        return models.User.model_validate(payload or {})

    def get_users(
        self,
    ) -> models.Users:
        """Get all user accounts.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(ops.BUILDERS["getUsers"]())
        return models.Users.model_validate(payload or {})

    def update_user(
        self,
        *,
        user_id: str,
        body: Any,
    ) -> models.User:
        """Update a user account.

        May be unavailable (admin); see docs/gating.md.
        """
        payload = self._send_json(ops.BUILDERS["updateUser"](user_id=user_id, body=body))
        return models.User.model_validate(payload or {})
