# Generated from src/forward_sdk/_async/services/_generated/wan_circuits.py by scripts/unasync.py -- do not edit.
# Edit the async source and re-run: uv run python scripts/unasync.py

"""WAN Circuits.

Generated by scripts/gen_services.py -- do not edit.
"""

from __future__ import annotations

from typing import Any

from forward_sdk._generated import models
from forward_sdk._ops import rest as ops
from forward_sdk._sync.services._base import Service

__all__ = ["WANCircuitsService"]


class WANCircuitsService(Service):
    """WAN Circuits."""

    def delete_wan_circuit(
        self,
        *,
        wan_circuit_name: str,
        network_id: str | None = None,
    ) -> Any:
        """Remove a WAN circuit.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["deleteWanCircuit"](
                network_id=self._network(network_id), wan_circuit_name=wan_circuit_name
            )
        )
        return payload

    def get_wan_circuit(
        self,
        *,
        wan_circuit_name: str,
        network_id: str | None = None,
    ) -> models.WanCircuit:
        """Get a WAN circuit.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getWanCircuit"](
                network_id=self._network(network_id), wan_circuit_name=wan_circuit_name
            )
        )
        return models.WanCircuit.model_validate(payload or {})

    def get_wan_circuits(
        self,
        *,
        network_id: str | None = None,
    ) -> models.WanCircuitList:
        """Get a network's WAN circuits.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["getWanCircuits"](network_id=self._network(network_id))
        )
        return models.WanCircuitList.model_validate(payload or {})

    def patch_wan_circuit(
        self,
        *,
        wan_circuit_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> models.WanCircuit:
        """Update a WAN circuit.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["patchWanCircuit"](
                network_id=self._network(network_id), wan_circuit_name=wan_circuit_name, body=body
            )
        )
        return models.WanCircuit.model_validate(payload or {})

    def put_wan_circuit(
        self,
        *,
        wan_circuit_name: str,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Add or replace a WAN circuit.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["putWanCircuit"](
                network_id=self._network(network_id), wan_circuit_name=wan_circuit_name, body=body
            )
        )
        return payload

    def put_wan_circuits(
        self,
        *,
        body: Any,
        network_id: str | None = None,
    ) -> Any:
        """Replace all of a network's WAN circuits.

        Uses the client's network when ``network_id`` is omitted.
        """
        payload = self._send_json(
            ops.BUILDERS["putWanCircuits"](network_id=self._network(network_id), body=body)
        )
        return payload
