"""Generate pydantic v2 models from the down-converted Forward OpenAPI spec.

Run via ``scripts/sync_spec.py``; kept separate so models can be regenerated
without re-copying the spec. Output is checked in and CI verifies it is fresh
(``scripts/check_generated.py``).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

OUTPUT = Path("src/forward_sdk/_generated/models.py")
INPUT = Path("spec/forward-openapi-3.1.json")

HEADER = "# generated by scripts/gen_models.py from spec/forward-openapi-3.1.json -- do not edit"

ARGS = [
    "--input-file-type",
    "openapi",
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--target-python-version",
    "3.10",
    "--base-class",
    "forward_sdk._generated._base.ForwardModel",
    "--snake-case-field",
    "--allow-population-by-field-name",
    "--extra-fields",
    "allow",
    "--use-standard-collections",
    "--use-union-operator",
    "--use-annotated",
    "--field-constraints",
    "--use-schema-description",
    "--use-field-description",
    "--collapse-root-models",
    "--reuse-model",
    "--use-subclass-enum",
    "--enum-field-as-literal",
    "none",
    "--disable-timestamp",
    "--formatters",
    "ruff-format",
    "--additional-imports",
    "forward_sdk._generated._base.OpenEnum",
    "--custom-file-header",
    HEADER,
]


# The generator always emits ``class X(str, Enum)``. Rebasing them on OpenEnum
# is done here rather than through a custom template because the generator
# pre-quotes docstrings only for its own templates; overriding the template
# would mean re-implementing that escaping.
ENUM_DECLARATION = re.compile(r"^class (\w+)\(str, Enum\):$", re.MULTILINE)


def retarget_enums(path: Path) -> int:
    """Rebase generated enums on :class:`OpenEnum` so unknown values validate.

    Forward adds enum members (vendors, device types, snapshot states) in
    ordinary releases. Strict enums would turn that additive server change into
    a client-side validation failure.
    """
    source = path.read_text(encoding="utf-8")
    source, count = ENUM_DECLARATION.subn(r"class \1(OpenEnum):", source)
    if count and "\nfrom enum import Enum\n" in source and "(Enum)" not in source:
        source = source.replace("\nfrom enum import Enum\n", "\n")
    path.write_text(source, encoding="utf-8")
    return count


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=INPUT)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)

    command = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(args.input),
        "--output",
        str(args.output),
        *ARGS,
    ]
    result = subprocess.run(command, check=False)
    if result.returncode != 0:
        return result.returncode

    enums = retarget_enums(args.output)

    print(f"wrote {args.output} ({args.output.stat().st_size // 1024} KB)")
    print(f"  enums rebased on OpenEnum: {enums}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
