"""Generate the NQE enum member lists from Forward's NQE data model.

The models in ``forward_sdk.models`` describe Forward's REST schema. NQE is a
separate namespace, and the two disagree about both type names and member names:
``device.platform.os`` has NQE type ``OS`` where the REST model is ``VendorOs``,
and NQE's ``Vendor`` has ``AZURE`` and ``GENERAL_DYNAMICS`` where the REST one
has ``MICROSOFT``, ``GD`` and ``IBM``. NQE's ``DeviceType`` has 16 members
describing what a device does; the REST one has 75 describing how it is
deployed. They are different concepts sharing a name.

Building a predicate from the REST names therefore produces queries Forward
rejects with *Unknown alternative*. This generator reads the NQE data model so
those names can be checked locally instead.

Source: ``docs/.generated/nqe-network-schema.json`` in the Forward monorepo,
which is what Forward's own published data-model pages are generated from.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _tidy import tidy

SCHEMA = Path("spec/nqe-network-schema.json")
OUTPUT = Path("src/forward_sdk/nqe/enums.py")

HEADER = '''"""Enum member names as NQE defines them.

Generated by scripts/gen_nqe_enums.py -- do not edit.

These are **not** the models in :mod:`forward_sdk.models`. Those describe
Forward's REST schema; NQE is a separate namespace that disagrees about both
type names and member names. Use these when building a query predicate, and the
models when reading a response back.

    >>> from forward_sdk.nqe.enums import members
    >>> "AZURE" in members("Vendor")
    True
    >>> "MICROSOFT" in members("Vendor")   # a REST name; NQE rejects it
    False
"""

from __future__ import annotations

from difflib import get_close_matches

__all__ = ["NQE_ENUMS", "members", "suggest"]

'''

FOOTER = '''

def members(type_name: str) -> frozenset[str]:
    """The members NQE accepts for ``type_name``, or empty if it is unknown.

    Every type in the current data model has at least one member, so an empty
    result means the type is not described here rather than that it has none.
    Treat that as "no information", not as "nothing is valid": refusing every
    value on the strength of an absent type would turn a gap in the model into a
    failure. ``type_name in NQE_ENUMS`` distinguishes the two if the invariant
    ever changes; a test asserts it currently holds.
    """
    return NQE_ENUMS.get(type_name, frozenset())


def suggest(type_name: str, member: str, *, limit: int = 3) -> list[str]:
    """Members of ``type_name`` close to ``member``, for an error message.

    A wrong member is usually a REST name reached for by mistake, and the NQE
    equivalent is often similar enough to find this way.
    """
    return get_close_matches(member, sorted(members(type_name)), n=limit, cutoff=0.6)
'''


def collect(node: Any, found: dict[str, set[str]]) -> None:
    """Walk the schema for ``OneOf`` types, which is how NQE models an enum."""
    if isinstance(node, dict):
        if node.get("type") == "OneOf" and node.get("name"):
            names = {
                alt["name"]
                for alt in node.get("alternatives", [])
                if isinstance(alt, dict) and alt.get("name")
            }
            found.setdefault(node["name"], set()).update(names)
        for value in node.values():
            collect(value, found)
    elif isinstance(node, list):
        for value in node:
            collect(value, found)


def render(enums: dict[str, set[str]]) -> str:
    lines = [HEADER, "#: NQE type name to the members NQE accepts for it."]
    lines.append("NQE_ENUMS: dict[str, frozenset[str]] = {")
    for name in sorted(enums):
        members_ = sorted(enums[name])
        lines.append(f'    "{name}": frozenset(')
        lines.append("        {")
        for member in members_:
            lines.append(f'            "{member}",')
        lines.append("        }")
        lines.append("    ),")
    lines.append("}")
    lines.append(FOOTER)
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, default=SCHEMA)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)

    if not args.schema.exists():
        raise SystemExit(
            f"{args.schema} not found. Sync it with scripts/sync_spec.py, which "
            "copies it from the Forward monorepo."
        )

    found: dict[str, set[str]] = {}
    collect(json.loads(args.schema.read_text(encoding="utf-8")), found)
    if not found:
        raise SystemExit("no OneOf types found; the schema shape may have changed")

    args.output.write_text(tidy(render(found), str(args.output)), encoding="utf-8")
    print(f"wrote {args.output}")
    print(f"  {len(found)} NQE enums, {sum(len(v) for v in found.values())} members")
    return 0


if __name__ == "__main__":
    sys.exit(main())
