"""Re-export the generated models under a public name.

Integrations annotate their own code with these types, and reaching into
``forward_sdk._generated`` to do it would tie them to a private module that
exists only because the models are generated. This writes the public
``forward_sdk.models`` surface, kept in step with the generator.

Every model is exported. Curating a subset would mean guessing which of the API's
types an integration will touch, and being wrong means someone reaches into the
private module anyway.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _tidy import tidy

MODELS_PATH = Path("src/forward_sdk/_generated/models.py")
OUTPUT = Path("src/forward_sdk/models/__init__.py")

CLASS_DECLARATION = re.compile(r"^class (\w+)\(", re.MULTILINE)

#: Types the SDK defines itself, alongside the generated ones, because they
#: describe endpoints Forward does not publish a schema for.
HAND_WRITTEN = (
    ("forward_sdk.nqe.repository", ("CommitReport", "DraftChange", "RepositoryQuery")),
    ("forward_sdk.nqe.query_ref", ("QueryRef", "SortKey")),
    ("forward_sdk.nqe.pagination", ("PageGuards",)),
)

HEADER = '''"""Types returned by the Forward API.

Generated by scripts/gen_public_models.py -- do not edit.

These are the models the SDK parses responses into. Import them from here rather
than from ``forward_sdk._generated``, which is an implementation detail::

    from forward_sdk.models import Device, Network, SnapshotInfo

Every model carries the fields Forward documents, and preserves any it does not:
unknown fields and unknown enum values survive round-tripping, so a Forward
release that adds either does not break an older SDK.
"""

from __future__ import annotations

'''


def model_names() -> list[str]:
    source = MODELS_PATH.read_text(encoding="utf-8")
    # Private helpers and the base class are not part of the public surface.
    return sorted(
        name
        for name in CLASS_DECLARATION.findall(source)
        if not name.startswith("_") and name not in {"ForwardModel", "OpenEnum"}
    )


def render(names: list[str]) -> str:
    lines = [HEADER]
    lines.append("from forward_sdk._generated._base import ForwardModel, OpenEnum")
    lines.append("from forward_sdk._generated.models import (")
    lines.extend(f"    {name}," for name in names)
    lines.append(")")
    for module, exports in HAND_WRITTEN:
        lines.append(f"from {module} import (")
        lines.extend(f"    {name}," for name in exports)
        lines.append(")")
    lines.append("")
    lines.append("__all__ = [")
    # Order does not matter here: tidy() runs ruff, which sorts __all__ itself.
    everything = sorted(
        {*names, "ForwardModel", "OpenEnum", *(n for _, e in HAND_WRITTEN for n in e)}
    )
    lines.extend(f'    "{name}",' for name in everything)
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)

    names = model_names()
    args.output.write_text(tidy(render(names), str(args.output)), encoding="utf-8")
    print(f"wrote {args.output}")
    print(f"  {len(names)} generated models re-exported")
    return 0


if __name__ == "__main__":
    sys.exit(main())
