"""Generate the operation table from the Forward OpenAPI description.

Reads the 3.2 source (not the down-converted copy) because down-converting
merges the operations Forward dispatches by a fixed query string onto a shared
path key, which would lose their individual parameters.

The generated table is the single source of truth for every operation's method,
path and fixed query. Hand-written request builders reference it by
``operationId`` (``@op("getNetworks")``), so a builder cannot drift from the
spec, and ``tests/spec/test_coverage.py`` uses it to prove every operation is
implemented exactly once.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl

import yaml

SPEC = Path("spec/forward-openapi.yaml")
UNPUBLISHED = Path("spec/unpublished.yaml")
GATING = Path("spec/gating.yaml")
OUTPUT = Path("src/forward_sdk/_generated/operations.py")

HTTP_METHODS = ("get", "put", "post", "delete", "options", "head", "patch", "trace")

#: A response in none of these is consumed incrementally rather than parsed as
#: one JSON document: an archive, a gzipped index, record-separated JSON.
DOCUMENT_MEDIA = ("application/json",)

FILE_HEADER = '''"""Operation table generated from the Forward OpenAPI description.

Generated by scripts/gen_operations.py -- do not edit.
"""

from __future__ import annotations

from forward_sdk._generated._defs import OpDef, ParamDef

__all__ = ["OPERATIONS"]

'''


def resolve(doc: dict[str, Any], node: Any) -> Any:
    """Resolve a local ``$ref`` one level; the joined spec only uses local refs."""
    seen = 0
    while isinstance(node, dict) and "$ref" in node:
        ref = node["$ref"]
        if not ref.startswith("#/"):
            raise ValueError(f"unexpected external ref: {ref}")
        target: Any = doc
        for part in ref[2:].split("/"):
            target = target[part.replace("~1", "/").replace("~0", "~")]
        node = target
        seen += 1
        if seen > 10:
            raise ValueError(f"ref cycle at {ref}")
    return node


def build_param(doc: dict[str, Any], raw: Any) -> dict[str, Any]:
    param = resolve(doc, raw)
    schema = resolve(doc, param.get("schema", {})) or {}
    enum = schema.get("enum") or []
    if not enum and "const" in schema:
        # A `const` parameter has exactly one legal value. Recording it as a
        # one-value enumeration lets the SDK supply it rather than making every
        # caller retype it.
        enum = [schema["const"]]
    if not enum:
        for variant in schema.get("oneOf", []) or schema.get("anyOf", []) or []:
            enum = resolve(doc, variant).get("enum") or enum
    description = param.get("description")
    return {
        "name": param["name"],
        "location": param["in"],
        "required": bool(param.get("required", param.get("in") == "path")),
        "explode": bool(param.get("explode", True)),
        "schema_type": schema.get("type"),
        "enum": tuple(str(v) for v in enum),
        "description": " ".join(description.split()) if description else None,
    }


def model_of(schema: Any) -> tuple[str | None, bool]:
    """Name the component schema a successful response returns.

    Lets generated service methods parse into the right model instead of
    handing back an untyped dictionary.
    """
    if not isinstance(schema, dict):
        return None, False
    ref = schema.get("$ref")
    if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
        return ref.rsplit("/", 1)[-1], False
    if schema.get("type") == "array":
        name, _ = model_of(schema.get("items"))
        return name, True
    return None, False


def collect(
    doc: dict[str, Any], stability: str, gating_by_tag: dict[str, list[str]]
) -> list[dict[str, Any]]:
    parents = {
        tag["name"]: tag.get("parent") for tag in doc.get("tags", []) if isinstance(tag, dict)
    }
    operations: list[dict[str, Any]] = []
    for path_key, raw_item in doc.get("paths", {}).items():
        item = resolve(doc, raw_item)
        bare, _, query = path_key.partition("?")
        fixed = tuple(
            (key, value or None) for key, value in parse_qsl(query, keep_blank_values=True)
        )
        shared = [build_param(doc, p) for p in item.get("parameters", [])]
        for method in HTTP_METHODS:
            operation = item.get(method)
            if not isinstance(operation, dict):
                continue
            params = shared + [build_param(doc, p) for p in operation.get("parameters", [])]
            deduped: dict[tuple[str, str], dict[str, Any]] = {}
            for param in params:
                deduped[(param["location"], param["name"])] = param
            tags = operation.get("tags") or ["Uncategorized"]
            tag = tags[0]
            request_body = resolve(doc, operation.get("requestBody", {})) or {}
            responses = operation.get("responses", {}) or {}
            response_media: set[str] = set()
            response_model: str | None = None
            response_is_array = False
            for status, response in sorted(responses.items()):
                if not str(status).startswith("2"):
                    continue
                content = resolve(doc, response).get("content") or {}
                response_media.update(content.keys())
                if response_model is None:
                    schema = (content.get("application/json") or {}).get("schema")
                    response_model, response_is_array = model_of(schema)
            operations.append(
                {
                    "operation_id": operation["operationId"],
                    "method": method,
                    "path": bare,
                    "tag": tag,
                    "fixed_query": fixed,
                    "parameters": tuple(deduped.values()),
                    "parent_tag": parents.get(tag),
                    "deprecated": bool(operation.get("deprecated", False)),
                    "request_media": tuple(sorted((request_body.get("content") or {}).keys())),
                    "response_media": tuple(sorted(response_media)),
                    "stability": operation.get("x-forward-stability", stability),
                    "gating": tuple(gating_by_tag.get(tag, ())),
                    "response_model": response_model,
                    "response_is_array": response_is_array,
                    "stream": bool(response_media)
                    and not any(m in DOCUMENT_MEDIA for m in response_media),
                    "summary": " ".join((operation.get("summary") or "").split()) or None,
                }
            )
    return operations


def render(operations: list[dict[str, Any]]) -> str:
    lines = [FILE_HEADER, "OPERATIONS: dict[str, OpDef] = {"]
    for op in sorted(operations, key=lambda o: o["operation_id"]):
        lines.append(f'    "{op["operation_id"]}": OpDef(')
        lines.append(f'        operation_id="{op["operation_id"]}",')
        lines.append(f'        method="{op["method"]}",')
        lines.append(f'        path="{op["path"]}",')
        lines.append(f'        tag="{op["tag"]}",')
        if op["fixed_query"]:
            lines.append(f"        fixed_query={op['fixed_query']!r},")
        if op["parameters"]:
            lines.append("        parameters=(")
            for param in op["parameters"]:
                bits = [f'name="{param["name"]}"', f'location="{param["location"]}"']
                if param["required"]:
                    bits.append("required=True")
                if not param["explode"]:
                    bits.append("explode=False")
                if param["schema_type"]:
                    bits.append(f'schema_type="{param["schema_type"]}"')
                if param["enum"]:
                    bits.append(f"enum={param['enum']!r}")
                lines.append(f"            ParamDef({', '.join(bits)}),")
            lines.append("        ),")
        if op["parent_tag"]:
            lines.append(f'        parent_tag="{op["parent_tag"]}",')
        if op["deprecated"]:
            lines.append("        deprecated=True,")
        if op["request_media"]:
            lines.append(f"        request_media={op['request_media']!r},")
        if op["response_media"]:
            lines.append(f"        response_media={op['response_media']!r},")
        if op["stability"] != "published":
            lines.append(f'        stability="{op["stability"]}",')
        if op["gating"]:
            lines.append(f"        gating={op['gating']!r},")
        if op["response_model"]:
            lines.append(f'        response_model="{op["response_model"]}",')
        if op["response_is_array"]:
            lines.append("        response_is_array=True,")
        if op["stream"]:
            lines.append("        stream=True,")
        if op["summary"]:
            summary = op["summary"].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'        summary="{summary}",')
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, default=SPEC)
    parser.add_argument("--unpublished", type=Path, default=UNPUBLISHED)
    parser.add_argument("--gating", type=Path, default=GATING)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)

    gating_by_tag: dict[str, list[str]] = {}
    if args.gating.exists():
        gating_by_tag = (yaml.safe_load(args.gating.read_text(encoding="utf-8")) or {}).get(
            "tags", {}
        ) or {}

    doc = yaml.safe_load(args.spec.read_text(encoding="utf-8"))
    operations = collect(doc, "published", gating_by_tag)
    published = len(operations)

    unpublished = 0
    if args.unpublished.exists():
        extra = yaml.safe_load(args.unpublished.read_text(encoding="utf-8")) or {}
        if extra.get("paths"):
            found = collect(extra, "unpublished", gating_by_tag)
            operations.extend(found)
            unpublished = len(found)

    counts = Counter(op["operation_id"] for op in operations)
    duplicates = sorted(name for name, count in counts.items() if count > 1)
    if duplicates:
        raise SystemExit(f"duplicate operationIds: {duplicates}")

    args.output.write_text(render(operations), encoding="utf-8")
    print(f"wrote {args.output}")
    print(f"  published operations: {published}")
    print(f"  unpublished operations: {unpublished}")
    print(f"  deprecated: {sum(1 for op in operations if op['deprecated'])}")
    print(f"  fixed-query dispatched: {sum(1 for op in operations if op['fixed_query'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
