"""Generate service classes for the long tail of Forward's API.

Five services are hand-written, because they are the paths integrations spend
their time in and deserve curated names and behaviour: networks, snapshots,
devices, device tags and NQE. The remaining twenty-odd groups are mechanical --
call the builder, parse the response into its model -- and are generated here.

Generating real source rather than conjuring methods at runtime keeps them
statically typed, visible to editors, and documentable by mkdocstrings, at the
cost of a file that must be regenerated when the spec changes. CI enforces that
with ``scripts/check_generated.py``.

Method names are the operationId in Python casing (``getLocations`` becomes
``get_locations``), so every method maps unambiguously onto Forward's own API
documentation.
"""

from __future__ import annotations

import argparse
import importlib.util
import keyword
import re
import sys
import types
from collections import defaultdict
from pathlib import Path
from typing import TYPE_CHECKING, Any

from _tidy import tidy

if TYPE_CHECKING:  # pragma: no cover - resolved statically, never imported at runtime
    from forward_sdk._generated._defs import OpDef

SOURCE_ROOT = Path("src")


def _load_isolated(module_name: str, path: Path) -> types.ModuleType:
    """Import one module without importing the package around it.

    This script writes part of ``forward_sdk``, so it cannot import the package
    normally: while the generated files are being replaced the package does not
    import cleanly, and the generator would fail exactly when it is needed.
    """
    if module_name in sys.modules:
        return sys.modules[module_name]
    for parent in ("forward_sdk", "forward_sdk._generated"):
        if parent not in sys.modules:
            package = types.ModuleType(parent)
            package.__path__ = [str(SOURCE_ROOT / Path(*parent.split(".")))]
            sys.modules[parent] = package
    spec = importlib.util.spec_from_file_location(module_name, path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


_defs = _load_isolated(
    "forward_sdk._generated._defs", SOURCE_ROOT / "forward_sdk/_generated/_defs.py"
)
_operations = _load_isolated(
    "forward_sdk._generated.operations",
    SOURCE_ROOT / "forward_sdk/_generated/operations.py",
)
OPERATIONS: dict[str, Any] = _operations.OPERATIONS

_CAMEL_BOUNDARY = re.compile(r"(?<=[a-z0-9])(?=[A-Z])")


def snake(name: str) -> str:
    """Mirror of :func:`forward_sdk._ops._generic.snake`, without the import."""
    converted = _CAMEL_BOUNDARY.sub("_", name).lower()
    return converted + "_" if keyword.iskeyword(converted) else converted


MODELS_PATH = Path("src/forward_sdk/_generated/models.py")
_CLASS_DECLARATION = re.compile(r"^class (\w+)\(", re.MULTILINE)


def _model_names() -> frozenset[str]:
    """Model classes available to reference.

    Read from the generated source rather than imported: this script writes part
    of the package, so it must not depend on the package importing cleanly.
    """
    return frozenset(_CLASS_DECLARATION.findall(MODELS_PATH.read_text(encoding="utf-8")))


MODEL_NAMES = _model_names()

OUTPUT_DIR = Path("src/forward_sdk/_async/services/_generated")

#: Groups with a hand-written service; see the module docstring.
HAND_WRITTEN_TAGS = frozenset(_defs.HAND_WRITTEN_TAGS)

HEADER = '''"""{title}.

Generated by scripts/gen_services.py -- do not edit.
{note}"""

from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from typing import Any

from forward_sdk._async.services._base import AsyncService
from forward_sdk._generated import models
from forward_sdk._ops import rest as ops

__all__ = ["{class_name}"]


class {class_name}(AsyncService):
    """{docstring}"""
'''


#: Typographic characters Forward uses in its summaries, mapped to ASCII so the
#: generated docstrings stay unambiguous.
PUNCTUATION = {
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2013": "-",
    "\u2014": "--",
    "\u2026": "...",
}


def plain(text: str) -> str:
    for fancy, ascii_form in PUNCTUATION.items():
        text = text.replace(fancy, ascii_form)
    return text


def module_name(tag: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", tag.lower()).strip("_")


def class_name(tag: str) -> str:
    parts = re.sub(r"[^A-Za-z0-9]+", " ", tag).split()
    return "Async" + "".join(p if p.isupper() else p.capitalize() for p in parts) + "Service"


def attribute_name(tag: str) -> str:
    return module_name(tag)


def _default_repr(value: object) -> str:
    return repr(value)


def render_method(operation: OpDef) -> str:
    """Render one service method for an operation."""
    name = snake(operation.operation_id)
    builder = f'ops.BUILDERS["{operation.operation_id}"]'

    has_network = any(p.name == "networkId" for p in operation.path_params)
    has_snapshot_query = any(p.name == "snapshotId" for p in operation.query_params)
    has_body = bool(operation.request_media)

    required: list[str] = []
    optional: list[str] = []
    forwarded: list[str] = []

    for param in operation.path_params:
        python_name = snake(param.name)
        if param.name == "networkId":
            optional.append(f"{python_name}: str | None = None")
            forwarded.append(f"{python_name}=self._network({python_name})")
        else:
            required.append(f"{python_name}: str")
            forwarded.append(f"{python_name}={python_name}")

    if has_body:
        required.append("body: Any")
        forwarded.append("body=body")

    dispatched = {key for key, _ in operation.fixed_query}
    for param in operation.query_params:
        if param.name in dispatched:
            continue
        python_name = snake(param.name)
        annotation = {
            "boolean": "bool | None",
            "integer": "int | None",
            "number": "float | None",
            "array": "Sequence[str] | None",
        }.get(param.schema_type or "", "str | None")

        if param.name == "snapshotId":
            optional.append(f"{python_name}: str | None = None")
            forwarded.append(f"{python_name}=self._snapshot({python_name})")
        elif param.required and len(param.enum) == 1:
            optional.append(f"{python_name}: str = {_default_repr(param.enum[0])}")
            forwarded.append(f"{python_name}={python_name}")
        elif param.required:
            required.append(f"{python_name}: {annotation.removesuffix(' | None')}")
            forwarded.append(f"{python_name}={python_name}")
        else:
            optional.append(f"{python_name}: {annotation} = None")
            forwarded.append(f"{python_name}={python_name}")

    signature = ", ".join(["self", "*", *required, *optional]) if (required or optional) else "self"
    call = f"{builder}({', '.join(forwarded)})" if forwarded else f"{builder}()"

    lines = [f"    async def {name}("]
    lines.append(f"        {signature},")
    lines.append(f"    ) -> {_return_annotation(operation)}:")
    lines.extend(_docstring(operation, has_network, has_snapshot_query))
    lines.extend(_body(operation, call))
    lines.append("")
    return "\n".join(lines)


def response_model(operation: OpDef) -> str | None:
    """The generated model for a response, when there is exactly one.

    A schema built from ``oneOf`` is emitted by the model generator as several
    classes (``NetworkEndpoint1`` and siblings), so there is no single type to
    parse into. Those return raw data rather than an arbitrary variant.
    """
    name = operation.response_model
    return name if name and name in MODEL_NAMES else None


def _return_annotation(operation: OpDef) -> str:
    if operation.stream:
        return "AsyncIterator[bytes]"
    name = response_model(operation)
    if name:
        model = f"models.{name}"
        return f"list[{model}]" if operation.response_is_array else model
    return "Any"


def _docstring(operation: OpDef, has_network: bool, has_snapshot: bool) -> list[str]:
    summary = plain(operation.summary or f"{operation.method.upper()} {operation.path}")
    if not summary.endswith("."):
        summary += "."
    lines = [f'        """{summary}']
    notes: list[str] = []
    if operation.deprecated:
        notes.append("Deprecated by Forward.")
    if operation.stability != "published":
        notes.append("Unpublished: not part of Forward's documented API.")
    if has_network:
        notes.append("Uses the client's network when ``network_id`` is omitted.")
    if has_snapshot:
        notes.append(
            "Uses the network's latest processed snapshot when ``snapshot_id`` is omitted."
        )
    if operation.gating:
        notes.append(f"May be unavailable ({', '.join(operation.gating)}); see docs/gating.md.")
    if notes:
        lines.append("")
        lines.extend(f"        {note}" for note in notes)
    lines.append('        """')
    return lines


def _body(operation: OpDef, call: str) -> list[str]:
    if operation.stream:
        return [
            f"        async with self._transport.stream({call}) as response:",
            "            async for chunk in response.aiter_bytes():",
            "                yield chunk",
        ]
    if operation.deprecated:
        lines = [
            "        warnings.warn(",
            f'            "{operation.operation_id} is deprecated in the Forward API",',
            "            DeprecationWarning,",
            "            stacklevel=2,",
            "        )",
        ]
    else:
        lines = []

    lines.append(f"        payload = await self._send_json({call})")
    name = response_model(operation)
    if name:
        model = f"models.{name}"
        if operation.response_is_array:
            lines.append(f"        return [{model}.model_validate(row) for row in payload or []]")
        else:
            lines.append(f"        return {model}.model_validate(payload or {{}})")
    else:
        lines.append("        return payload")
    return lines


def render_module(tag: str, operations: list[OpDef]) -> str:
    name = class_name(tag)
    note = ""
    if any(op.stability != "published" for op in operations):
        note = "\nThese endpoints are not part of Forward's published API.\n"
    docstring = f"{tag}."
    if any(op.gating for op in operations):
        gating = sorted({g for op in operations for g in op.gating})
        docstring += (
            f"\n\n    May be unavailable on your instance ({', '.join(gating)}); "
            "see docs/gating.md.\n    "
        )
    body = HEADER.format(title=tag, note=note, class_name=name, docstring=docstring)
    methods = "\n".join(render_method(op) for op in operations)
    module = body + "\n" + methods
    if "warnings.warn(" in module:
        module = module.replace(
            "from __future__ import annotations\n",
            "from __future__ import annotations\n\nimport warnings\n",
            1,
        )
    return module


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT_DIR)
    args = parser.parse_args(argv)

    by_tag: dict[str, list[OpDef]] = defaultdict(list)
    for operation in OPERATIONS.values():
        if operation.tag not in HAND_WRITTEN_TAGS:
            by_tag[operation.tag].append(operation)

    args.output.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    exports: list[tuple[str, str, str]] = []
    tag_attributes: list[tuple[str, str]] = []

    for tag, operations in sorted(by_tag.items()):
        operations.sort(key=lambda op: op.operation_id)
        path = args.output / f"{module_name(tag)}.py"
        path.write_text(tidy(render_module(tag, operations), str(path)), encoding="utf-8")
        written.append(path.name)
        exports.append((module_name(tag), class_name(tag), attribute_name(tag)))
        tag_attributes.append((tag, attribute_name(tag)))

    init = [
        '"""Service classes generated from the Forward API description.',
        "",
        "Generated by scripts/gen_services.py -- do not edit.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import TYPE_CHECKING",
        "",
    ]
    for module, cls, _ in exports:
        init.append(f"from forward_sdk._async.services._generated.{module} import {cls}")
    init.extend(
        [
            "",
            "if TYPE_CHECKING:  # pragma: no cover",
            "    from forward_sdk._async.transport import AsyncTransport",
            "",
            "__all__ = [",
        ]
    )
    init.extend(
        f'    "{name}",'
        for name in sorted(["AsyncGeneratedServices", *(cls for _, cls, _ in exports)])
    )
    init.extend(
        [
            "]",
            "",
            "",
            "class AsyncGeneratedServices:",
            '    """The API groups whose services are generated.',
            "",
            "    Declared as attributes rather than attached dynamically so that type",
            "    checkers and editors can see them.",
            '    """',
            "",
        ]
    )
    init.extend(f"    {attribute}: {cls}" for _, cls, attribute in exports)
    init.extend(
        [
            "",
            "    def _attach_generated_services(self, transport: AsyncTransport) -> None:",
        ]
    )
    init.extend(f"        self.{attribute} = {cls}(transport)" for _, cls, attribute in exports)
    init.extend(
        [
            "",
            "",
            "#: API group name to the client attribute carrying its service.",
            "SERVICE_TAGS: dict[str, str] = {",
        ]
    )
    init.extend(f'    "{tag}": "{attribute}",' for tag, attribute in sorted(tag_attributes))
    init.append("}")
    init.append("")
    init_path = args.output / "__init__.py"
    init_path.write_text(tidy("\n".join(init), str(init_path)), encoding="utf-8")

    print(f"wrote {len(written)} service modules to {args.output}")
    print(f"  {sum(len(ops) for ops in by_tag.values())} methods across {len(by_tag)} groups")
    return 0


if __name__ == "__main__":
    sys.exit(main())
